### ISSUE TITLE
Unclear installation documentation (RENAMED: webpack sass-resources-loader issue)

### ISSUE THREAD

**Issue by mgmanoj** [scandipwa/base-theme#100]
**Describe the bug**
On running "npm run watch" or "npm run build" command returns error

**To Reproduce**
1. Go to vendor/scandipwa/source
2.do 'npm run build'
3. See error

**Expected behavior**
I guess this will generate static files for production. Also expect to see the new theme on frontend site(When theme is selected)

**Desktop (please complete the following information):**
 - OS: cent OS
 - Version : Magento 2.3.1

**Error details**
ERROR in ./src/app/component/CategoryShoppingOptions/CategoryShoppingOptions.style.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-resources-loader/lib/loader.js):
Error: 
      Something wrong with provided resources.
      Make sure 'options.resources' is String or Array of Strings.
....

**Comment by alfredsgenkins** [comment]
The `npm run build` should never happen in `vendor/scandipwa/source`. It is intended to be run from `app/design/...`. Please make sure there are no `node_modules` in `vendor/scandipwa/source`. Please refer to [docs](https://github.com/scandipwa/base-theme/blob/master/docs/04-Webpack.md) for more info.

**Comment by alfredsgenkins** [comment]
@mgmanoj Please update on this, if docs were not clear enough! If possible, provide expected information to be updated. Ideally, create a PR.
