### ISSUE TITLE
As low as is shown on a Configurable product even though product options do not differ in price

### ISSUE THREAD

**Issue by lion152** [scandipwa/base-theme#1006]
**Description**:

As low as is shown on a Configurable product even though product options do not differ in price.
In the product cart component, the only check for the "as low as" to be shown is whether the product is configurable or not.

**Expected behavior**:

We should check if there is a price difference between the configurable product options, and if yes only then apply "as low as" label

**To Reproduce**:
1. Go to demo.scandipwa.com
2. Go to the United Kingdom store
3. Open PLP
4. All configurable products have "as low as" label

**Versions**:
- ScandiPWA 3.0.2

**Additional context**:
Originally reported by @ionmeri on GitHub, but had a wrong reason listed as the bug origin

**Comment by alfredsgenkins** [comment]
@lianastaskevica is this such an issue indeed? Magento 2 template does show `As low as` always. In this template: `/vendor/magento/module-configurable-product/view/base/templates/product/price/final_price.phtml`.

I am closing this issue. Please reopen, if you consider this a bug anyway. @lianastaskevica @lion152
