### ISSUE TITLE
Unable to log in when auth_token expires

### ISSUE THREAD

**Issue by andsvateles** [scandipwa/base-theme#1022]
**Description**:
When the auth_token set in local storage is expired (after default 3600 seconds) it's impossible to log in again without reloading the page.

**Expected behavior**:
To show the login-form when clicking the "my account" icon even when auth_token has expired.

**Screenshots, Video, Logs**
https://streamable.com/xqa12b
Showing example by removing "auth_token" manually from local storage. Same behavior if waiting 3600 seconds for expiration.

**To Reproduce**:
1. Go to startpage
2. Login with any user
3. Clear the "auth_token" local storage (to replicate it expiring)
4. Try to log in without refreshing the browser.

**Versions**:
- https://demo.scandipwa.com/ (as of today)

**Comment by lianastaskevica** [comment]
Was fixed in https://github.com/scandipwa/base-theme/issues/1549
