### ISSUE TITLE
Menu do not shows if not build with subitems

### ISSUE THREAD

**Issue by drc0** [scandipwa/base-theme#1023]
**Description**:
The default menu do not appears if using a flat structure, I need to put a custom link for example and all items under that link, then on frontend only the second level is shown, the custom link used as parent is not.

**Expected behavior**:
being able to use a flat link structure, probably I missed something in the documentation?

**Comment by lion152** [comment]
This looks like a question, could you please post it on our [forum](https://forum.scandipwa.com/). Please, do not use GitHub issues for asking questions. If it will turn out to be a bug it will be transfered here.

**Comment by drc0** [comment]
@lion152 thanks for your answer but I considered it a bug because if putting some menu items from the backend it did nothing on the frontend, maybe I should open a bug here https://github.com/scandipwa/menu-organizer for the documentation to require a base "All" item to be created before all the other and put them as child?
