### ISSUE TITLE
Theme setup issue

### ISSUE THREAD

**Issue by mgmanoj** [scandipwa/base-theme#105]
**Describe the bug**
demo storefront is not displaying correctly.

**To Reproduce**
1. bootstrap theme
2. do "run npm build"
3. do 'php bin/magento setup:static-content:deploy -f'

**Expected behavior**
Storefront displays without any error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac OS
 - Browser- chrome
 - magento 2.3.1

**Additional context**
<img width="1136" alt="Screenshot 2019-04-11 at 11 36 13 AM" src="https://user-images.githubusercontent.com/13735397/55934401-10c41080-5c4e-11e9-8f89-689bfbed929e.png">

**Comment by eli-l** [comment]
Hi @mgmanoj 
Would you please provide PHP server logs? I'm afraid I'm not able to help without you providing it.
You're welcome to join our Slack: https://scandipwa.com/#subscribe-slack

**Comment by mgmanoj** [comment]
@eli-l Sorry to miss that. server log indicates "main.ERROR: Redis is not configured for persistent queries". But redis is configured for page as well as default caching. Also one slide in slide manager and cms blocks are added

**Comment by eli-l** [comment]
@mgmanoj 
You will find all explanations in https://github.com/scandipwa/persisted-query README's **Config** section.
