### ISSUE TITLE
MiniCart is not synced with CartItem

### ISSUE THREAD

**Issue by rkokarevics** [scandipwa/base-theme#109]
**Description:**
On the cart page, updating quantities in MiniCart, does not update the quantity value in CartItem component and vice versa.

** Steps to reproduce the behavior: **
1. Add any product to the cart
2. Hover over the minicart icon and click on 'View Cart'
3. Hover over the minicart icon again and click on the '+' or '-' to increase or decrease the quantity of product in the cart

**Expected behavior**
CartItem list quantity for updated product changes as well and it should be the same as the one in minicart for the chosen product

**Screenshots**
![image](https://user-images.githubusercontent.com/47378697/55965032-73350500-5c7e-11e9-8695-d77d6cf099a5.png)
![image](https://user-images.githubusercontent.com/47378697/55965108-9495f100-5c7e-11e9-8d43-63f0f43c7a8b.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**
The same happens if you change the quantity in CartItem list. Quantity in Minicart is not updated, so the user will see 2 different quantities.

**Comment by alfredsgenkins** [comment]
Should be tested on checkout branch.
