### ISSUE TITLE
Home slider is not dynamic

### ISSUE THREAD

**Issue by mgmanoj** [scandipwa/base-theme#112]
**Describe the bug**
Static image is showing instead of newly added image when new slide is enabled for home page slider using Magento backend.

**To Reproduce**
1. Go to slider management on scandipwa menu in Magento backend
2. Add new slider and upload a new image then enable it.
3. Go to storefront
4. See slider is present but image URL is wrong or not correct

**Expected behavior**
Home slider showing uploaded slide image

 - OS: Mac os
 - Browser - chrome
 - Version Magento 2.3.1

The theme is installed using composer

**Comment by alfredsgenkins** [comment]
Do you cleared Magento cache?

**Comment by mgmanoj** [comment]
> Have you cleared Magento cache?

yes. I could see multiple images tag rendered on html which are not uploaded.
<img width="579" alt="Screenshot 2019-04-12 at 12 49 12 PM" src="https://user-images.githubusercontent.com/13735397/56019246-c57b3200-5d21-11e9-8216-da33c8341488.png">

**Comment by alfredsgenkins** [comment]
Okey. Could flush varnish cache? Go to varnish and execute: `varnishadm ban req.url "~ /"`.

**Comment by mgmanoj** [comment]
@alfredsgenkins varnish is not installed in my environment

**Comment by fjaatheen** [comment]
Hello Alfreds @alfredsgenkins ,

I have the same issue, I also tried to add a banner using magento page builder, the header with the menu, logo and search is not loaded, I use Scandipwa 6.2.2 on existing magento 2.4.6, php 8.1.2, node 14.18.1

Appreciate your help.
