### ISSUE TITLE
Show placeholders on Homepage and Footer

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#12]
**Is your feature request related to a problem? Please describe.**
The placeholders are not visible when loading a homepage and in footer. This makes a website blink a little bit every time it is being reloaded on a homepage.

**Describe the solution you'd like**
There is a necessity to add placeholders for slider and following CMS block. 

**Describe alternatives you've considered**
The question is will we make a "common CMS placeholder" or we will create a custom one for every element present on page?

**Additional context**
There already were a placeholders for Slider. They just went missing. Homepage component must be investigated.

**Comment by ainarssondors** [comment]
Reserving issue for myself.
