### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by matlae-ugly** [scandipwa/base-theme#1266]
**Description**:
Implement reset password action, style email and password reset page.

**Comment by matlae-ugly** [comment]
The issue was resolved in another project management software. Transferred to GitHub for full transparency.

**Comment by matlae-ugly** [comment]
The issue was resolved in another project management software. Transferred to GitHub for full transparency.

**Comment by matlae-ugly** [comment]
The issue was resolved in another project management software. Transferred to GitHub for full transparency.

**Comment by denissfedutins** [comment]
hey @matlae-ugly, where can I find this fix (PR)?
