### ISSUE TITLE
Remove the visible placeholder boundary on PDP images

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#13]
**Is your feature request related to a problem? Please describe.**
The images on PDP are blinking due placeholders being shown before the image load.

**Describe the solution you'd like**
I would like to remove the visible placeholder boundary (the grey square) around the loading images. They appear very fast, and if the same transition effect will be implemented (the same as on Category page) the loading might become super-seamless.

**Describe alternatives you've considered**
There is an option to leave everything as it is, but this would decrease the UX.

**Comment by ainarssondors** [comment]
Reserving the issue for myself.
