### ISSUE TITLE
Enforce 'react/jsx-no-bind' eslint rule usage

### ISSUE THREAD

**Issue by atachh** [scandipwa/base-theme#131]
**Describe the feature**
Arrow functions inside render() is considered an anti-pattern because it causes a brand new function to be created with every re-render.

**Describe the solution you'd like**
1) Replace existing constructions similar to `onClick={ (e) => this.handleClick(e) }` with `onClick={ this.handleClick }` and bind the function in the constructor like that `this.handleClick = this.handleClick.bind(this)`.
2) Add 'react/jsx-no-bind' rule to eslintrc config to prevent further usage of arrow functions inside render().

**Comment by alfredsgenkins** [comment]
Could you please open a PR?

**Comment by atachh** [comment]
> Could you please open a PR?

Nothing to show yet. Will do after there is some result
