### ISSUE TITLE
ScandiPWA Local Setup Automation: Linux Mint

### ISSUE THREAD

**Issue by matlae-ugly** [scandipwa/base-theme#1310]
**Description**:
*To Do*
Optimize the script (Removing hardcoded values)
Test the script in different browsers (Safari, Firefox)
Prepare VB images for testing (Linux Mint)
Test the script on the different OS versions (Linux Mint)

**Comment by lion152** [comment]
The issue was resolved in another project management software. Transferred to GitHub for full transparency.
