### ISSUE TITLE
Best Match Issue

### ISSUE THREAD

**Issue by lion152** [scandipwa/base-theme#1319]
**Description**:

The search result page "Best Match" and default selection is not sorting by search result relevance, but product positions.

**Expected behavior**:

"Best match" should sort by the result relevance

**Comment by alfredsgenkins** [comment]
What is "result relevance"? How to manage this? Position is defined as `Best Match` becuse it is commonly used to position some elements on-top of others to promote product A, B, C while keeping other results according the relevance.

**Comment by lianastaskevica** [comment]
Best match if the sort by position. Closing the task since it is the expected behavior.
