### ISSUE TITLE
Resizing the browser on desktop always shows the menu

### ISSUE THREAD

**Issue by drc0** [scandipwa/base-theme#1329]
**Description**:
The menu blocks the page content when the browser is shrunk to "mobile sizes"

**Expected behavior**:
Even if use agent is used to detect if we are on mobile, media queries should be used to show things on various screen sizes

**Screenshots, Video, Logs**
![menu](https://user-images.githubusercontent.com/5507633/94239030-77f08600-ff11-11ea-8e4c-43ff520ac0f6.png)

**Versions**:
- ScandiPWA: 3.1

**Comment by lion152** [comment]
Unable to reproduce on the latest version
