### ISSUE TITLE
Inconsistent currency formatting

### ISSUE THREAD

**Issue by drc0** [scandipwa/base-theme#1330]
**Description**:
In the minicart the currency symbol comes after the amount on the overlay and before the amount on the items list.
Generally speaking hard coding the currency and spacing position is bad, optimally the Intl library should be used to consistently format currency symbol, spacing, and amount https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat .  
**Expected behavior**:
Consistent currency formatting

**Versions**:
- ScandiPWA: 3.1.1

**Comment by drc0** [comment]
@alfredsgenkins please merge also https://github.com/scandipwa/base-theme/pull/1542 because in production mode a call to formatPrice was done inside __() and the function was not found breaking the frontend.
thanks

**Comment by alfredsgenkins** [comment]
Merged!
