### ISSUE TITLE
Step by Step - Install procedure in DOCS

### ISSUE THREAD

**Issue by tomekjordan** [scandipwa/base-theme#134]
**Is your feature request related to a problem? Please describe.**
Can you please add Step by Step Install docs?
Quick HOW TO for newbies?

I installed from your installer and got clean slow Magento theme.
BUT where is PWA? How to make it similar to your demo site? I expected I will work and look similar,
especially you mentioned that install is easy,fast. But know I see this is not fully working PWA theme.

**Describe the solution you'd like**
Steps to setup PWA theme.
How to install it - whats required - react, dependencies on server
for Debian/Ubuntu/Centos
How to run the theme in PWA mode, how to make it look like similar to your demo site?

**Comment by alfredsgenkins** [comment]
Did you switched the theme in M2 backend? You have to enable ScandiPWA theme in M2 backend or directly in database. The demo content is not provided with installer package. The [scandipwa-base](https://github.com/scandipwa/scandipwa-base) does. Follow quick start guide there.

Regarding dependancies on server: apart from default M2 environment, you will need an LTS node, to run npm install scripts, and initially compile a theme. More docs regarding theme compilation can be found [here](https://github.com/scandipwa/base-theme/blob/master/docs/04-Webpack.md). Please note `npm run build` has to be run manually from `app/design/[PATH TO THEME ROOT]`. It is done automatically in upper mentioned [scandipwa-base](https://github.com/scandipwa/scandipwa-base) docker setup.

Regarding quick start: we are planning to update the documentation and release multiple how-to video-guides in the near future (upcoming week or two). I will keep this issue open, please let me know, if you still have any additional questions @tomekjordan !

**Comment by tomekjordan** [comment]
Hi. Yes, I have Lts installed (the latest 11),
but I guess I missed the part with compilation. 

I was convinced its done by installer :)
Anyway when I run
/app/design/frontend/Scandiweb/pwa/npm run build
it gives me:
```
> scandipwa-base@1.0.0 build /home/admin/domains/*********.com/public_html/app/design/frontend/Scandiweb/pwa
> npm run build-sw && webpack --config ./src/config/webpack.production.config.js

> scandipwa-base@1.0.0 build-sw /home/admin/domains/********.com/public_html/app/design/frontend/Scandiweb/pwa
> webpack --config ./src/config/webpack.sw.config.js --mode=production

sh: webpack: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! scandipwa-base@1.0.0 build-sw: `webpack --config ./src/config/webpack.sw.config.js --mode=production`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the scandipwa-base@1.0.0 build-sw script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/admin/.npm/_logs/2019-04-18T20_43_10_610Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scandipwa-base@1.0.0 build: `npm run build-sw && webpack --config ./src/config/webpack.production.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scandipwa-base@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/admin/.npm/_logs/2019-04-18T20_43_10_676Z-debug.log
```

node_modules? which ones? how to install them?
Thanks for clarification

**Comment by eli-l** [comment]
Installer is just a helper to bootstrap a theme, while theme itself must be built each time changes were made.
Looks like you are just missing node dependencies: please run “npm ci” before running “npm run build”.

**Comment by tomekjordan** [comment]
Hi. yes, you were right npm ci fixes some things. Looks like theme have compiled.
But some other problems appeared.
Looks like theme use incorrect paths to static files. I'm getting blank page with some errors in console:

```
http://*******.coml/static/static/frontend/Scandiweb/pwa/en_US/Magento_Theme/assets/font/MuliBold.woff2 net::ERR_ABORTED 404 (Not Found)
(index):1 Refused to apply style from http://*******.coml/static/static/frontend/Scandiweb/pwa/en_US/Magento_Theme/main.css?83fddcff97b3ced656dd' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
(index):5 GET http://*******.coml/static/static/frontend/Scandiweb/pwa/en_US/Magento_Theme/83fddc.bundle.js?83fddcff97b3ced656dd 404 (Not Found)
favicon.ico:1 GET http://*******.coml/static/frontend/Scandiweb/pwa/en_US/Magento_Theme/assets/favicon/favicon.ico 404 (Not Found)
```

Checked and all static files are deployed in pub/static but they cannot be succesfully located
![Screenshot_49](https://user-images.githubusercontent.com/8250276/56433676-0353f980-62d2-11e9-86bd-c7c576c2212b.png)

Any hints?

**Comment by eli-l** [comment]
Does the problem persists in developer mode with dynamic assets?
If problem persists and you think that's because /pub is missing - you might have your server misconfigured. Please set webroot to <magento_installation>/pub as per article: https://devdocs.magento.com/guides/v2.3/install-gde/tutorials/change-docroot-to-pub.html

**Comment by tomekjordan** [comment]
Yes, it persist in devloper mode.
My Magento is configured correctly. Because normal themes and extensions are working without any problems.
I installed it manually from ZIP, by using composer and by using Installatron. So 3 ways cannot fail

**Comment by leeroybrun** [comment]
I had the same issue and was using Bitnami Magento image which is not using pub/ directory as root directory. I lost a lot of time and could not figure out why I was getting these 404 errors and tried to reinstall multiples times until I figured out it was linked to the webroot directory.

I changed the configuration in Apache config files (following the guide @eli-l provided) and now the ScandiPWA theme is loading fine.

Maybe I missed something, but I don't think it's explained somewhere else than here that the webroot should be the pub/ folder for the theme to work. May be worth adding somewhere in the doc/installer! :-)

**Comment by eli-l** [comment]
Hi @leeroybrun 
Thank you for sharing the details, we'll take it into a count in the future, so far we will add this as a note to prevent confusions.

Right now we are not testing compatibility with 3rd party setups, especially the ones that ignores official security recommendations. Setting root to ./pub folder is explained in details in Magento 2 official doc: https://devdocs.magento.com/guides/v2.3/install-gde/tutorials/change-docroot-to-pub.html

**Comment by eli-l** [comment]
Note was added to README.md https://github.com/scandipwa/base-theme/commit/822ad51e02592e52a190b1707546f31c7e6c952e

**Comment by tomekjordan** [comment]
Docroot to pub docs for Apache at Magento docs doesnt cover DEBIAN install were path to www is different
and you have Magento installed in:
/home/admin/domains/domain.com/public_html/

**Comment by Manisha-Vasani** [comment]
Hi @eli-l ,

I have run “npm ci” before running “npm run build”. but, still facing error :

/var/www/html/scanpwa/app/design/frontend/Scandiweb/pwa/node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:30
                } catch {}
                        ^

SyntaxError: Unexpected token {
    at NativeCompileCache._moduleCompile (/var/www/html/scanpwa/app/design/frontend/Scandiweb/pwa/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/var/www/html/scanpwa/app/design/frontend/Scandiweb/pwa/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/var/www/html/scanpwa/app/design/frontend/Scandiweb/pwa/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/var/www/html/scanpwa/app/design/frontend/Scandiweb/pwa/node_modules/terser-webpack-plugin/dist/index.js:26:38)
    at Module._compile (/var/www/html/scanpwa/app/design/frontend/Scandiweb/pwa/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/var/www/html/scanpwa/app/design/frontend/Scandiweb/pwa/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/var/www/html/scanpwa/app/design/frontend/Scandiweb/pwa/node_modules/terser-webpack-plugin/dist/cjs.js:3:16)
    at Module._compile (/var/www/html/scanpwa/app/design/frontend/Scandiweb/pwa/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/var/www/html/scanpwa/app/design/frontend/Scandiweb/pwa/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/var/www/html/scanpwa/app/design/frontend/Scandiweb/pwa/src/config/webpack.sw.config.js:19:22)
    at Module._compile (/var/www/html/scanpwa/app/design/frontend/Scandiweb/pwa/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
