### ISSUE TITLE
Product information tab scrolling bottom of the page in mobile

### ISSUE THREAD

**Issue by jari646** [scandipwa/base-theme#1363]
**Description**:
When you open tab product information tab what have long text, page will scroll down and you need to scroll up to see text.

**To Reproduce**:
Example here with mobile phone
https://demo.scandipwa.com/hp-efi-designer-edition-5-1-468772.html

**Comment by robertsbriedis** [comment]
PR: https://github.com/scandipwa/base-theme/pull/1384
