### ISSUE TITLE
Impossible to change logo

### ISSUE THREAD

**Issue by EmilsBre** [scandipwa/base-theme#1367]
**Description**:

Added logo for the first time and it worked. Then tried to change it. I upload the logo but it doesn't change on frontend, but in admin panel it shows that it is changed. Tried to delete it but still stays there. Flushed cache storage and magento cache. Also tried in incognito but the old logo still appears on the site. 

**Versions**:
- ScandiPWA: V3
- Browser version: Safari Version 13.1.1 (15609.2.9.1.2)

**Comment by robertsbriedis** [comment]
Can't reproduce the issue.
Steps did:
1. Went to Admin -> Content -> Configurations -> Selected store ( Main Website Store )
2. Heading -> Added logo image.
3. Cache Manager -> Flash cache storage.
4. Did it multiple times and checked on chrome and safari, each time logo updated.
