### ISSUE TITLE
Colour swatch borders should be added so can be seen on white background

### ISSUE THREAD

**Issue by EmilsBre** [scandipwa/base-theme#1368]
**Description**:
White swatch colour can't be seen on white background. Also tick can't be seen because its white. A border could be added so it would be there at all times. They can't be seen both on PDP and PLP. 
<img width="1440" alt="Screenshot 2020-10-02 at 14 44 02" src="https://user-images.githubusercontent.com/72255902/94919870-dabbc180-04bd-11eb-8148-59048f22f0b1.png">
<img width="1440" alt="Screenshot 2020-10-02 at 14 44 27" src="https://user-images.githubusercontent.com/72255902/94919889-e5765680-04bd-11eb-84bd-026ad84a0fb7.png">

https://ishop-knb-1601297783.scandipwa.cloud/microsoft-laptop-34.html?memory_size=5454

**Comment by robertsbriedis** [comment]
Can't reproduce on the demo site.
1. Went to https://de-demo.scandipwa.com/n-black-sunglasses-2.html?size=7834&color=7827
2. Checked styling for the color switcher.

![Screenshot 2020-10-05 at 14 28 57](https://user-images.githubusercontent.com/51077929/95074470-4f3d6d00-0717-11eb-8699-7bbb475824ed.png)
