### ISSUE TITLE
Plugin docs are outdated

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#1370]
**Description**:
1. This link: https://docs.scandipwa.com/docs/plugin-mechanism.html has some missleading information about plugins. In example the "index.js" file for their listing.
2. No up-to-date video tutorials are present 

**Expected behavior**:
1. There is no need for such file in latest plugin iteration implementation. You can just put files in plugin folder. 
2. Video tutorials are updated

**Comment by yeegor** [comment]
The text documentation has been updated and currently should be 100% relevant.
The video guides should still be refilmed.

**Comment by lianastaskevica** [comment]
Closing the tasks since the new video is filmed already
