### ISSUE TITLE
Migrations of slider and menu do not run

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#1375]
**Description**:
Slider Manager menu under SCANDIWEB option gives an error like this Base table or view not found: 1146 Table 'magento.scandiweb_slider' doesn't exist, query was: SELECT COUNT(*) FROM `scandiweb_slider` AS `main_table`  I check in the database the table scandiweb_slider doesn't exist. However the module Scandiweb_Slider is active. 

**Expected behavior**:
Migration should have happended. This issue us caused by `setup_version` missing in the vendor/scandipwa/slider/etc/module.xml file.

Just edit this file and add setup_version="0.0.1" like <module name="Scandiweb_Slider" setup_version="0.0.1">
after that execute the bin/magento setup:upgrade

**Additional context**:
Originally reported by Amir Teshome and fix proposed by Sanchit.

**Comment by alfredsgenkins** [comment]
Merged, released, closing.

**Comment by TechDriven** [comment]
Thank you @alfredsgenkins

**Comment by jazib93** [comment]
Hello, I'm unable to run the php bin/magento setup:upgrade command successfully. It throws this error "Base table or view not found: 1146 Table 'dbname.scandiweb_slider_slide' doesn't exist". I checked the tables in the database. The table is there but the module is unable to pick up the table prefix. it should be like this "dbname.tableprefixtablename".

**Comment by forzaana** [comment]
> Hello, I'm unable to run the php bin/magento setup:upgrade command successfully. It throws this error "Base table or view not found: 1146 Table 'dbname.scandiweb_slider_slide' doesn't exist". I checked the tables in the database. The table is there but the module is unable to pick up the table prefix. it should be like this "dbname.tableprefixtablename".

have you solve the problem ?
