### ISSUE TITLE
Layered Navigation Values Non-Expanded state

### ISSUE THREAD

**Issue by manikumaran1978** [scandipwa/base-theme#1381]
**Description**:
Currently on the category page, all the atrributes and thei values are in expanded state. it is difficult for the user to scroll through.
https://demo.scandipwa.com/computers-peripherals-accessories.html

Is it possible to have the values in non-expanded state like in this page ?
http://staging.kelderscomfortschoenen.nl/dames-comfortschoenen/veterschoenen.html

**Comment by alfredsgenkins** [comment]
Closed this with a comment: https://github.com/scandipwa/base-theme/pull/1405#issuecomment-706279029

Please refer to this issue for a solution: https://github.com/scandipwa/base-theme/issues/1388
