### ISSUE TITLE
Catalog Product List widget does not respect Magento 2 configurations on the front-end

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#1387]
ISSUE

Catalog Product List widget does not respect Magento 2 configurations on the front-end. When selecting different display rules, the same products are rendered on the front-end each time. 

STEPS TO REPRODUCE

1. Open admin->content->pages->homepage
2. Expand the content tab of homepage CMS
3. Add new widget 
4. Select Catalog product list widget
5. Choose SKU in the conditions 
6. Select one product SKU to be shown in the widget
7. Save page
8. Notice there are more products on the FE and none of them is matching the needed SKU

EXPECTED RESULT

All conditions under the catalog product list widget are supported and respected on the front-end

**Comment by santosh-gaggle** [comment]
getting the same issue please resolved it ASAP.
https://github.com/scandipwa/base-theme/issues/1546
