### ISSUE TITLE
Footer Redesign

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#1390]
DESING

DESKTOP - ![Group 3.png](https://app.gitkraken.com/api/glo/boards/5f451d3f3d9b050011b75e3c/attachments/5f7ddcdd0d832b001119f16d)
MOBILE - ![footer mobile.png](https://app.gitkraken.com/api/glo/boards/5f451d3f3d9b050011b75e3c/attachments/5f7de0c06ddf520011282d77)

TODO
* Restyle the footer on desktop and mobile based on the provided design
* Style existing footer block according to the design on both desktop and mobile 
** Add the content from the design
** As background for the footer block use the secondary base color
* Style the copyright notice on mobile and desktop as per design
** As  background for copyright notice use secondary hover color

EXPECTED RESULT
* Footer CMS block is styled on mobile and desktop 
* Footer copyright notice is styled on mobile and desktop 
* Footer colors use secondary base values and are managed by the color configurations

**Comment by alfredsgenkins** [comment]
@lianastaskevica current implementation by @robertsbriedis does look alright, but has all menu items hard-coded in the `Footer.config.js`. Maybe we should post-pone this task to next sprint and add new BE component to it - create a new ScandiPWA menu for it? Or CMS? If not, can merge this PR.
