### ISSUE TITLE
Slider zoom/onClick error

### ISSUE THREAD

**Issue by robertsbriedis** [scandipwa/base-theme#1395]
**Description**:
While clicking on a slider sometimes error appears might be related to zoom/scrolling on the image.

**Expected behavior**:
Clicking and zooming work without errors.

**To Reproduce**:
1. Go PDP
2. Open console.
2. Click on Slider sides and check if the error appears.
<img width="706" alt="Screenshot 2020-10-08 at 00 53 29" src="https://user-images.githubusercontent.com/51077929/95436981-21496a00-095d-11eb-98c2-d597be2fe7ee.png">

**Versions**:
- ScandiPWA: 3.0.0
- Chrome

**Comment by lion152** [comment]
Will be resolved by Image zoom redesign in #1397
