### ISSUE TITLE
Slider zoom - don't zoom window when image zoomed to max

### ISSUE THREAD

**Issue by robertsbriedis** [scandipwa/base-theme#1396]
**Description**:
Might be good if when we scroll/zoom the slider image to the max then we don't allow to zoom windows as well. For me personally, it feels quite messy.
And zoom sensitive could be less, as for desktop it's crazy fast and for mobile slow.

Expected behavior:
1. Zoom don't zoom window.
2. Scrolling has not so sensitive zooming.

**Comment by lion152** [comment]
Will be resolved by Image zoom redesign in https://github.com/scandipwa/base-theme/issues/1397
