### ISSUE TITLE
Newsletter in the footer / M2 Support

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#1398]
Magento 2 has a newsletter subscription in the footer field by default. We need to implement support for this feature. 

DESIGN
https://prnt.sc/uvgu4q

TODO
* Add newsletter subscription field to the footer 
* Style it as per design on both mobile and desktop
* Add placeholder text "Enter your email address"
** The text should be translatable 
* The orange button in the design indicates the submit button 
** On click on the submit button, the customer should be subscribed to the newsletter 
* Add email validation to the subscription field (same as during checkout)
* On submit button:
** trigger email validation
*** if email failed validation, reuse email field behavior such as we have in checkout ( change bolder color to red and show “Email is invalid.” https://prnt.sc/sx9zq7)
*** show success notification if the email was added to the newsletter subscription. Use the following text: “You’ve successfully subscribed to our newsletter”
*** The text should be translatable
*** If validation is correct, the email address is added to the newsletter subscribers list

EXPECTED RESULT
* Newsletter subscription in the footer is styled 
* Email validation is present
* Success/error notifications are shown
* Customers can be subscribed to newsletter

**Comment by teodormoq** [comment]
I already made this.
Alfreds suggested me to make a plugin but i dont really have time for this, so who ever is going to make this task is welcome to make my code both backend and frontend. :) 

https://github.com/scandipwa/base-theme/pull/915
