### ISSUE TITLE
Implement a custom select for product sorting on Category Page

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#14]
**Is your feature request related to a problem? Please describe.**
The sorting "dropdown" select is not descriptive enough. It is hard to understand that this is a select, not a simple box. Additionally, this select shows a native dropdown, which looks cheap.

**Describe the solution you'd like**
We need to implement a custom dropdown. Preferably in `Field` component. Preferably w/ any 3rd party dependencies. 

**Describe alternatives you've considered**
There is an option to just add the arrow to select. But in my opinion, this would be a cool feature to have all UI elements available styled out-of-the-box.

**Comment by ainarssondors** [comment]
Reserving issue for myself.
