### ISSUE TITLE
Contact Us / M2 Support

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#1402]
We need to implement support for the default Magento contact us form

**TODO**

* Add new core page /contact. No need to be present in Magento BE.
* This page should be enabled based on the setting value in admin->stores->configuration->general->contacts->Enable Contact Us
* Page title should be "Contact Us"
** Title should be translatable 
* Add "name", "email", "phone number", "what's o your mind?" fields. 
** What's on your mine is text area 
** All labels should be translatable
 ** Name, email, whats on your mind fields are required
* Add submit button under the contact form
** On click on submit button, the error/success notifications should be shown
** Notification text should be translatable
* Email should be sent to the email address specified in admin->stores->configuration->general->contacts->email options->send emails to

**EXPECTED RESULT**

* Contact us page is created
* Contact us page is enabled/disabled based on the admin configurations
* Contact us emails are sent

**Comment by zans-laksa** [comment]
Added new module scandipwa/contact-graphql
Related pull requests:
- scandipwa/base-theme#1705 
- scandipwa/customization#6
