### ISSUE TITLE
User Experience improvement for content cusotmizations

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#1423]
**Description**:

Currently, to change the content of some default CMS blocks in the theme, users need to first find this block on the FE, inspect it and copy the HTML with all needed classes, then create a new block in admin and assign it in stores configs. 

The whole process is very confusing for users. 

**How we need to improve it**

We need to add the CMS blocks to the demo DB so the users can easily manage the content. 

**List fo CMS blocks with the content**:
https://manual.scandipwa.com/basic-configuration/color-and-content-customization - see content customization

**Comment by AleksandrsKondratjevs** [comment]
https://github.com/scandipwa/sample-data/pull/3
