### ISSUE TITLE
mixins still can't be overriden in v3

### ISSUE THREAD

**Issue by raivisdejus** [scandipwa/base-theme#1425]
**Description**:
Site always uses mixns from vendor, overriding mixin does not work. Mixins are loaded with `sass-resources-loader` in
https://github.com/scandipwa/base-theme/blob/3.x-dev/src/config/webpack.production.config.js#L140
and
https://github.com/scandipwa/base-theme/blob/3.x-dev/src/config/webpack.development.config.js#L190

**Expected behavior**:
1. On bootstrapping the theme vendor mixin and variable files (aka SASS resources) are copied to theme folder and webpack uses them.

**To Reproduce**:
1. override `src/vendor/scandipwa/source/src/app/style/abstract/_media.scss` mixin by copying to your theme
2. Add new breakpoint
3. When attempting to use the new breakpoint site will crash

**Versions**:
- ScandiPWA: 3.1.0

**Comment by lianastaskevica** [comment]
Hey @raivisdejus! The issue is fixed in the Create ScandiPWA App - https://scandipwa.gitbook.io/create-scandipwa-app/
