### ISSUE TITLE
Order sucess page never shows for magento default payment methods

### ISSUE THREAD

**Issue by manikumaran1978** [scandipwa/base-theme#1435]
**Description**:
When an order is placed using the magento's default available payment methods such as bank transfer the order sucess page never shows and the page is stuck with the below screen but order is created in admin
![no order sucess](https://user-images.githubusercontent.com/36991113/96233672-0dc38200-0fa1-11eb-8cc3-ad34a66e5ce1.png)

**Expected behavior**:
Order sucess page should show

**Versions**:
- ScandiPWA: 3.1.4

**Comment by aleksandrakorolova** [comment]
Can't reproduce on ScandiPWA 3.2.1
https://drive.google.com/file/d/1ckdq8c2pbuJws_JDycFZc4SXuMTinl73/view?usp=sharing
