### ISSUE TITLE
"Image not found" appears if no category image is added

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#1449]
**Description**:
"Image not found" appears if no category image is added

**Expected behavior**:
No "image not found" is visible 

**Screenshots, Video, Logs**
![Screenshot 2020-10-19 at 17 50 03](https://user-images.githubusercontent.com/52198221/96467381-85104480-1233-11eb-90de-15936ef80578.png)

**To Reproduce**:
1. Open category on magento admin
2. make sure no image is added
3. open the category on FE
4. notice the image not found text

**Comment by robertsbriedis** [comment]
The issue is that in DB for that specific category we have a URL for an image that doesn’t exist.
To test go to category add image and then remove, image not found text will be gone.
