### ISSUE TITLE
Top navigation menu overlapping with the slider

### ISSUE THREAD

**Issue by lion152** [scandipwa/base-theme#1454]
**Description**:

The top navigation menu is overlapping with the slider.

The issue can be seen on the https://demo.scandipwa.com/

**Expected behavior**:

The top navigation menu does not overlap with the slider or any other elements

**Screenshots, Video, Logs**

![image](https://user-images.githubusercontent.com/4339464/96585943-f231e180-12e8-11eb-884f-5d36e4dd8155.png)

**Comment by robertsbriedis** [comment]
Talked with Levs and we couldn't reproduce this anymore.
