### ISSUE TITLE
Sort order not working for Layered navigation attribute options

### ISSUE THREAD

**Issue by santosh-gaggle** [scandipwa/base-theme#1458]
**Description**:
Sort order not working for Layered navigation attribute options
at category page filter not showing according to sort order also it's value

**Expected behavior**:
it should show according to sort order

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/56184739/96693330-bbb99c80-13a4-11eb-9d28-74fa8132e66c.png)

**To Reproduce**:
1. Go to category page 
2. you can see there filter now showing according to sort order value

**Versions**:
- ScandiPWA: 3.1.5
-Magento 2.3.5-p2

**Comment by santosh-gaggle** [comment]
@alfredsgenkins  please fix this issue.

**Comment by lianastaskevica** [comment]
closing as a duplicate of https://github.com/scandipwa/base-theme/issues/1420
