### ISSUE TITLE
Cannot login 

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#1459]
**Description**:
An error message appears when logging in with both an existing account or wrongs credentials - message: "Variable "$_guest_quote_id_0" got invalid value null; Expected non-nullable type String! not to be null."

**Expected behavior**:
I am logged in if credentials are correct
The error message of the wrong access appears if credentials are wrong

**To Reproduce**:
1. Login 
2. See error message

**Comment by lianastaskevica** [comment]
cannot reproduce

**Comment by yeegor** [comment]
@lianastaskevica which version are you unable to reproduce this on? I believe I have seen this in the latest release.

**Comment by AleksandrsKondratjevs** [comment]
@yeegor Tried to login in version 3.1.5. For me login is working okey and no errors appears. And with not correct credentials it shows error as expected.

**Comment by yeegor** [comment]
@AleksandrsKondratjevs try clearing the local storage and logging in before adding anything to cart.

**Comment by AleksandrsKondratjevs** [comment]
@yeegor Yes, now see, after clearing storage bug appears! Will then process with it.
