### ISSUE TITLE
Wrong Myaccount query signature for generateCustomerToken

### ISSUE THREAD

**Issue by drc0** [scandipwa/base-theme#1494]
**Description**:
Requiring a guest quote id lets the user login/password_reset/etc.. operation fail if the guest doesn't have a cart id pending

**Expected behavior**:
respect the signature of customer-graph-ql/src/etc/schema.graphqls that doesn't require a guest_quote_id

**Versions**:
- ScandiPWA: 3.1.5

**Comment by lianastaskevica** [comment]
Closing the issue as a duplicate of https://github.com/scandipwa/base-theme/issues/1459. The PR is already created here - https://github.com/scandipwa/base-theme/pull/1490
