### ISSUE TITLE
Show VAT Number on Storefront (new Account Options) / M2 Support

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#1499]
**Description**:
Determines if a Value Added Tax number is visible on the storefront. In ScandiPWA, the VAT number is never visible on the storefront. https://docs.magento.com/user-guide/customers/account-options-new.html?itm_source=merchdocs&itm_medium=quick_search&itm_campaign=federated_search&itm_term=show%20vat%20number

**TODO**:
Implement support for the feature

**Comment by zans-laksa** [comment]
Fixed PR requested changes
