### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by raivisdejus** [scandipwa/base-theme#150]
**Is your feature request related to a problem? Please describe.**
Stores tend to exist in multiple languages, support for different language UIs is helpful.

**Describe the solution you'd like**
**1. Source**
All translation strings would be wrapped in a translation function `t('My string')`. 
The translation function should have option to have placeholders and provide data for the placeholders `t('My string with {{ placeholder }}', {placeholder: 'Some placeholder value'})`

**2. Translation extraction**
There should be some automated way to get all the translation keys, so it is easy to get new strings that need translating. A webpack module like [webpack-extract-translation-keys](https://github.com/grassator/webpack-extract-translation-keys) could be used to extract new translations

Translations for each language can be stored in a separate file and updated as needed.

**3. Use of translations**
To minimize boilerplate and avoid importing a particular translation function in every module that needs translations a [Webpack Provide plugin](https://webpack.js.org/plugins/provide-plugin/) could be used to provide the translation function globally

**4. Translation function**
Any implementation of translation function can be used. One option could be [translate-js](https://github.com/dbrekalo/translate-js#readme)

Example implementetion of the `t()` could be
```
import translate from 'translate-js';
import translationsEn from 'translations-en_US.json';

translate.setLocale('en');
translate.add(translationsEn);

const t = function (string, templateData, options) {
    return translate(string, templateData, options);
}

export { t };
```

**Comment by alfredsgenkins** [comment]
This will be done as a Enterprise version of ScandiPWA theme.
