### ISSUE TITLE
Wrong canonicals for categories and product pages

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#1512]
**Description**:
Wrong canonical URLs are present in the website.
On M2.3, latest swpwa version - https://prnt.sc/v7cwlv
On M2.4, latest swpwa version - https://prnt.sc/v7cwvn

**Task**
Rewire and make sure that PDPs and PLPs canonical contains absolute URL.

E.g. https://demo.scandipwa.com/2-power-10-8v-2300mah-li-ion-l-5419863.html should have https://demo.scandipwa.com/2-power-10-8v-2300mah-li-ion-l-5419863.html as canonical. NOT 2-power-10-8v-2300mah-li-ion-l-5419863.html

**Expected behavior**:
An absolute canonical URL is presented for each PLP & PDP.

**Comment by AleksandrsKondratjevs** [comment]
Hello ! 
No bug at here, just canonical tags are disabled by default. So when theme tries to get value it gets null and puts it into canonical tag. 
To enable canonical tags for products/categories:
Go to stores->configuration->catalog->seo

Also added into sample data to enable canonical tags when setting it.
https://github.com/scandipwa/sample-data/pull/2
