### ISSUE TITLE
Schema markup review is missing "Author" fields

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#1513]
**Bug description**

Products' review snippets are missing "Author" fields are missing - https://prnt.sc/ua5dd8 which makes review snippets unusable. e.g on https://medisave.indvp.com/us_en/product/basic-aneroid-black-70 page

**TASK**:

Add the "Author" field based on documentation provided by Google (Microdata)
Documentation for review snippet - https://developers.google.com/search/docs/data-types/review-snippet

**Expected outcome:**

The author field is applied to reviews with review author passed to the field
No errors spotted in rich-results testing tool

**How to test it:**

Copy page code to https://search.google.com/test/rich-results
No errors should appear in "Review snippets"

**Comment by AleksandrsKondratjevs** [comment]
Hello!
Can't reproduce issue. Author field is present.

Version: Scandipwa 3.1.5

How I tested:
1. Created new review for products
2. Approve it via admin panel
3. Entered code from FE to https://search.google.com/test/rich-results
4. Result shows that author field is present and where it is located
![review_test1](https://user-images.githubusercontent.com/68007919/97702493-c1576680-1ab7-11eb-819e-2494991fca1f.png)
![review_test](https://user-images.githubusercontent.com/68007919/97702502-c3b9c080-1ab7-11eb-853a-95ebad79685d.png)
