### ISSUE TITLE
Products don't sort by price on category page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/base-theme#1535]
**Description**:
Products don't sort by price on category page

**Expected behavior**:
Products sort by price (Low -High) on category page

**To Reproduce**:
1. Open website
2. Select sort by 'price (low-high)'

**Actual result**:
Products order changes but it not correct

**Additional context**:
Price high-low doesn't work too

**Comment by lianastaskevica** [comment]
![Screenshot 2020-11-09 at 10 48 59](https://user-images.githubusercontent.com/52198221/98519263-2e69b980-2279-11eb-9ccc-25376ca63755.png)
see https://scandipwapmrev.indvp.com/default/women/women-dresses?sortKey=price&sortDirection=ASC

**Comment by aleksandrakorolova** [comment]
Can't reproduce

**Comment by niraligajera** [comment]
Same issue price hight to low not working for some category. return 500 error and when we check log their no details about error.
