### ISSUE TITLE
Error fetching category when adding CMS block 

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#1537]
**Description**:
When a CMS block is added to a category, an error fetching category appears. 

**Expected behavior**:
No error appears, CMS block is displayed in the category

**To Reproduce**:
1. Open admin->catalog->categories->open catedory in edit->expand content tab->add "displayed CMS block" 
2. Save category
3. Open category on the FE
4. Notice error fetching config

**Branch**
3.1.6-rc

**Comment by AleksandrsKondratjevs** [comment]
Hello!
https://github.com/scandipwa/cms-graphql/pull/13
I suggest this PR from community should make a thing. Checked locally  and all works on magento 2.4.0.
