### ISSUE TITLE
new product widget not showing the correct products

### ISSUE THREAD

**Issue by santosh-gaggle** [scandipwa/base-theme#1546]
**Description**:
New product widget not showing the correct products
when we apply the new product widget on the cms page, then it should show new products but it shows random products.

**Expected behavior**:
new product widget should show the new product which product have 'news_form_date' and 'news_to_date'

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/56184739/97480162-10e34880-1979-11eb-9136-077cb21f5c31.png)

here you can see in the image that i used "products(filter: { news_to_date: { eq:"1999-10-28"} }) "
for this query it should show the 0 result but it's show the products and if we change "eq" to "gteq" or "lteq" then also showing the same result.
![image](https://user-images.githubusercontent.com/56184739/97480552-95ce6200-1979-11eb-922b-e9951cd6f834.png)

 

**To Reproduce**:
1. add new product widget from admin for the home page
2. you will see that these products are not new 

**Versions**:
- ScandiPWA:3.1.5
-Magento 2.3.5-p2

**Comment by lianastaskevica** [comment]
Fixed in ScandiPWA 3.2.0
