### ISSUE TITLE
Color attribute is broken on product page if set 'no' in Visible on Catalog Pages in Admin panel

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/base-theme#1558]
**Description**:
Color attribute is broken on product page if set 'no' in Visible on Catalog Pages in Admin panel

**Expected behavior**:
Color attribute near product is missing on category page. Color attribute is displayed on product page -> user can select color and buy product

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/73526235/97666611-b89a6c80-1a86-11eb-8d96-7a51fba1f0ab.png)

**To Reproduce**:
1. Open Color attribute in the Admin panel
2. Select 'no' in Visible on Catalog Pages on Storefront field
3. Save -> Flush Cache Storage
4. Open website -> Open product which has color attribute

**Actual result**:
Color attribute is broken

**Notes**:
It works expected on category page

**Comment by lianastaskevica** [comment]
This is the expected behavior. 
Visible on Catalog Pages on Storefront - determines if the attribute is visible on PDP
Used in product listing - determines if the attribute is visible on product pods on PLP
