### ISSUE TITLE
Never-ending loader when user opens order popup (information)

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/base-theme#1566]
**Description**:
Never-ending loader when user opens order popup (information)

**Expected behavior**:
Pop up with order popup opens

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/73526235/97709263-b5bd6d00-1ac2-11eb-8890-d3d4206fc9ae.png)
![image](https://user-images.githubusercontent.com/73526235/99943700-604f4580-2d7a-11eb-9288-d43a423df5aa.png)

**To Reproduce**:
1. Log in
2. Open Order page
3. Open order

**Actual result:**:
Never-ending loader

**Comment by zans-laksa** [comment]
Related pull request: scandipwa/quote-graphql/pull/46
