### ISSUE TITLE
Products stay on the cart when guest complete order

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/base-theme#1569]
**Description**:
Products stay on the cart when guest complete order

**Expected behavior**:
Cart is empty

**To Reproduce**:
1. Open website
2. Add products to cart
3. Complete order
4. Open home page 

**Actual result:**:
Products stay on the cart 

**Additional context**:
If user logged in and then done the same steps - products disappear from the cart

**Comment by lianastaskevica** [comment]
Fixed in 3.1.6
