### ISSUE TITLE
User doesn't see error message when he logged in with incorrect or disabled account

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/base-theme#1579]
**Description**:
User doesn't see error message when he logged in 

**Expected behavior**:
Error message 'The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.' appears 

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/73526235/97991104-a3f10800-1de9-11eb-8f9b-29420b72fb5f.png)

**To Reproduce**:
1. Open website
2. Enter login and password (for example, aleksandra.korolova@scandiweb.com/Scandipwa123)
3. Tap 'Sign in'

**Actual result:**:
Nothing happens on the storefront. The error appears in the console

**Comment by lianastaskevica** [comment]
Cannot reproduce on ScandiPWA 3.2.1
