### ISSUE TITLE
Error message appears if user selected checkbox 'Create account', entered register email and taped 'Proceed to billing' on shipping step

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/base-theme#1589]
**Description**:
Checkbox 'Create new account' is not selected 
+ Can't go to the billing step, error message 'A customer with the same email address already exists in an associated website.' appears

**Expected behavior**:
Checkbox selected

**Screenshots, Video, Logs**
https://drive.google.com/file/d/1ce3-7xxrQJnKK5YcyCA-uNLEE3ioJ2G3/view?usp=sharing

**To Reproduce**:
1. Add products to cart
2. Open cart
3. Select checkbox 'Create account'
4. Enter register account
5. Delete it

**Actual result:**:
Checkbox is not selected
If user selects checkbox 'Create account', an email field is displayed

**Notes**:
Step:
1. Add products to cart
2. Open cart
3. Select checkbox 'Create account'
4. Enter register account (Don't log in)
5. Fill all mandatory fields
6. Tap 'Proceed to billing'

Actual result: 
Can't go to the billing step, error message 'A customer with the same email address already exists in an associated website.' appears

**Comment by polander** [comment]
What is expected behaviour for the second part of this issue?

**Comment by aleksandrakorolova** [comment]
@polander If a user entered register email, create account form changes to sign-in form (password not a mandatory field). And the user goes to the billing step.
