### ISSUE TITLE
Error during compilation when upgrading to 3.1.6 on Magento 2.3.5

### ISSUE THREAD

**Issue by lion152** [scandipwa/base-theme#1591]
**Description**:
Upgrading to 3.1.6 on Magento 2.3.5 fails, see logs

**Expected behavior**:
Can upgrade ScandiPWA to 3.1.6 on Magento 2.3.5

**Screenshots, Video, Logs**

`Compilation was started.
1804%message% 0/8 [>---------------------------]   0% < 1 sec 64.5 MiBProxies code generation... 0/8 [>------------------------]   0% < 1 sec 64.5 MiB
1805Proxies code generation... 1/8 [===>---------------------]  12% < 1 sec 68.5 MiB
1806Repositories code generation... 1/8 [==>-----------------]  12% < 1 sec 68.5 MiB
1807Repositories code generation... 2/8 [=====>--------------]  25% 6 secs 203.0 MiB
1808Service data attributes generation... 2/8 [===>----------]  25% 6 secs 203.0 MiB
1809Application code generator... 3/8 [=====>--------]  37% 6 secs 203.0 MiB
1810Application code generator... 4/8 [=======>------]  50% 10 secs 229.0 MiB
1811Interceptors generation... 4/8 [=======>------]  50% 10 secs 229.0 MiB
1812Interceptors generation... 5/8 [========>-----]  62% 21 secs 261.0 MiB
1813Area configuration aggregation... 5/8 [========>-----]  62% 21 secs 261.0 MiB
1814Area configuration aggregation... 6/8 [==========>---]  75% 25 secs 359.0 MiB
1815Interception cache generation... 6/8 [==========>---]  75% 25 secs 359.0 MiBErrors during compilation:
1816	ScandiPWA\CmsGraphQl\Model\Resolver\DataProvider\Block
1817		Extra parameters passed to parent construct: $searchCriteriaBuilder. File: /var/www/public/vendor/scandipwa/cms-graphql/src/Model/Resolver/DataProvider/Block.php
1818Total Errors Count: 1
1819[2020-11-02 18:35:24] main.ERROR: Error during compilation #0 /var/www/public/setup/src/Magento/Setup/Module/Di/Code/Reader/Decorator/Interceptions.php(85): Magento\Setup\Module\Di\Compiler\Log\Log->report() #1 /var/www/public/setup/src/Magento/Setup/Module/Di/App/Task/Operation/InterceptionCache.php(59): Magento\Setup\Module\Di\Code\Reader\Decorator\Interceptions->getList('/var/www/public...') #2 /var/www/public/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\InterceptionCache->doOperation() #3 /var/www/public/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(206): Magento\Setup\Module\Di\App\Task\Manager->process(Object(Closure), Object(Closure)) #4 /var/www/public/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #5 /var/www/public/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #6 /var/www/public/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\DiCompileCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #7 /var/www/public/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #8 /var/www/public/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #9 /var/www/public/bin/magento(23): Symfony\Component\Console\Application->run() #10 {main} [] []
1820
1821In Log.php line 92:
1822                            
1823  Error during compilation  
1824                            
1825
1826setup:di:compile
1827`

there is problem with the `ScandiPWA\CmsGraphQl` module upon `magento:setup:di:compile`

**Versions**:
- ScandiPWA: 3.1.6
- Magento 2.3.5

**Additional context**:
Originally reported by @danielsstabulis

**Comment by lianastaskevica** [comment]
Hello @lion152. Unfortunately, we do not plan to support old Magento versions now. Please upgrade your Magento version:)
