### ISSUE TITLE
Cart price rules don't work

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/base-theme#1599]
**Description**:
Cart price rules don't work

**Expected behavior**:
Cart price rule works ($10discount applies to order)

**To Reproduce**:
1. Open cart rule or create new (for example, discount $10 if subtotal >$100 in cart
2. Set active it
3. Open website -> Add products to the card (total amount >$100)

**Actual result:**:
$10 discount is missing

**Comment by lianastaskevica** [comment]
Cannot reproduce on ScandiPWA 3.2.0 ![Screenshot 2020-11-09 at 10 47 03](https://user-images.githubusercontent.com/52198221/98519046-e9458780-2278-11eb-8eaa-b010093e7ff4.png)
