### ISSUE TITLE
Using same image for multiple slides breaks slider

### ISSUE THREAD

**Issue by kandrejevs** [scandipwa/base-theme#161]
**Describe the bug**
Slider uses image as key, if you use same image for multiple slides you get slides with same key

**To Reproduce**
1. create slider with slides that use the same image, observe warnings in console
```
Warning: Encountered two children with the same key, `/media/slides/secondary-slider-background.svg`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```
**Expected behavior**
key is unique to slide not to image

**Comment by alfredsgenkins** [comment]
Is not the case anymore (since `2.x`)
