### ISSUE TITLE
Can't add a page to the home screen on Android 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/base-theme#1619]
**Description**:
Can't add a page to the home screen on Android 

**Expected behavior**:
Alers opens with a question (do you want....?) -> user answers 'yes' -> page is added to home screen

**To Reproduce on Android**:
1. Open website 
2. Tap 'Add to Home Page'

**Actual result**:
Nothing happens when clicking 'Add to homepage'

**Comment by lianastaskevica** [comment]
closing as a duplicate of https://github.com/scandipwa/base-theme/issues/966
