### ISSUE TITLE
Logged user can't complete order, if we don't Allow Guest Checkout 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/base-theme#1645]
**Description**:
Logged user can't complete order, if we don't Allow Guest Checkout 

**Expected behavior**:
Logged user can complete order

**To Reproduce**:
1. Log in
2. Add product to cart
3. Complete shipping step
4. Choose the payment method
5. Tap 'Complete order'

**Actual result:**:
Error message 'Close Guest checkout is not allowed. Register a customer account or login with existing one.' appears. Can't complete order

**Comment by riha112** [comment]
[PR for this issue](https://github.com/scandipwa/quote-graphql/pull/43)
