### ISSUE TITLE
Checkbox with price range isn't selected if user selected it

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/base-theme#1651]
**Description**:
Checkbox with price range isn't selected

**Expected behavior**:
Checkbox is selected
Like this:
![image](https://user-images.githubusercontent.com/73526235/98678774-c0e88680-2367-11eb-801a-d5e62f0f0641.png)

**Screenshots, Video, Logs**
https://drive.google.com/file/d/14pI_3unVFEkOa3tSYZGvE0m_LyHNM7Cq/view?usp=sharing

**To Reproduce**:
1. Open some category
2. Select a price range

**Actual result**:
Products in this price interval are displayed on category page, but checkbox with price range isn't selected

**Notes**:
If user select again this checkbox, checkbox will be selected

**Comment by lianastaskevica** [comment]
Cannot reproduce on the latest ScandiPWA version
