### ISSUE TITLE
Opera, Edge: Indent is missing between ‘continue shopping’ button and footer on the completed order page 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/base-theme#1659]
**Description**:
Indent is missing between the ‘continue shopping’ button and footer on the completed order page 

**Expected behavior**:
Add Indent between button and footer

**To Reproduce**:
1. Open website
2. Add product to cart
3. Complete order

**Actual result**:
Indent is missing between ‘continue shopping’ button and footer on the completed order page 
![opera](https://user-images.githubusercontent.com/73526235/98910369-bcd57980-24cb-11eb-9e8e-8654d589ea80.PNG)

**Additional context**:
Windows: Opera, edge

**Comment by lianastaskevica** [comment]
Closing as a duplicate of https://github.com/scandipwa/base-theme/issues/1683
