### ISSUE TITLE
iOs 13 and 14: White keyboard appears when user tap the password field 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/base-theme#1667]
**Description**:
What is wrong? What happened?

**Expected behavior**:
Keyboard appears
![image](https://user-images.githubusercontent.com/73526235/98919022-037ca100-24d7-11eb-9032-27d7800b5b03.png)

**To Reproduce**:
1. Open website
2. Open sign in page
3. Enter email
4. Tap the password field

**Actual result:**:
White keyboard appears when user tap the password field 
![image](https://user-images.githubusercontent.com/73526235/98918805-bf899c00-24d6-11eb-9e5a-01f9615b86f6.png)
![image](https://user-images.githubusercontent.com/73526235/98918846-c9130400-24d6-11eb-8a59-cec322cab4c0.png)

**Additional context**:
iOS 13 and 14: Safari and Chrome

**Comment by lianastaskevica** [comment]
Cannot reproduce on a real device, iOS 14.
