### ISSUE TITLE
Magento 2.3.5 compilation fails with ScandiPWA 3.1.6 and scandipwa/cms-graphql 1.4.2

### ISSUE THREAD

**Issue by romeof1980** [scandipwa/base-theme#1687]
**Description**:
run `magento setup:di:compile`

**Expected behavior**:
successfully compiles

**Actual result*
Errors during compilation: ScandiPWA\CmsGraphQl\Model\Resolver\DataProvider\Block
		Extra parameters passed to parent construct: $searchCriteriaBuilder. File: /var/www/public/vendor/scandipwa/cms-graphql/src/Model/Resolver/DataProvider/Block.php

**Reason*
in vendor/scandipwa/cms-graphql/src/Model/Resolver/DataProvider/Block.php on line 48 you can see:
`parent::__construct($blockRepository, $widgetFilter, $searchCriteriaBuilder);`
should be instead:
`parent::__construct($blockRepository, $widgetFilter);`

**Versions**:
- ScandiPWA: (use `composer info scandipwa/source`):   3.1.6
- Any other composer module, you thing could be related:   scandipwa/cms-graphql 1.4.2
- Magento 2.3.5

**Additional context**:
parent::__construct calls the following class:
src/vendor/magento/module-cms-graph-ql/Model/Resolver/DataProvider/Block.php

thanks and have a great day!
romeo

**Comment by lianastaskevica** [comment]
Hello @romeof1980! Unfortunately, we do not plan to support old Magento versions. Please upgrade to Magento 2.4:)
