### ISSUE TITLE
Review Query error on Magento 2.3.5

### ISSUE THREAD

**Issue by teodormoq** [scandipwa/base-theme#1707]
**Description**:
When upgrade to scandipwa version 3.2.0 when the this error happens, that is because magento changed the way their review graphql works
https://devdocs.magento.com/guides/v2.4/graphql/queries/product-review-ratings-metadata.html

This will not work on Magento 2.3.5, so maybe there should be made a support so scandipwa still supports 2.3.5.
(The reason that scandipwa maybe still should support 2.3.5 is because of a lot of magento modules still dont support ^2.4, so many is not upgrading their magento version yet.)

**Expected behavior**:
No Error and review works

**Screenshots, Video, Logs**
![Screenshot 2020-11-16 at 10 51 15](https://user-images.githubusercontent.com/8639654/99238155-b01d9200-27f9-11eb-81f1-c330e32040a1.png)

**Versions**:
- ScandiPWA: 3.2.0
- Magento: 2.3.5

**Comment by lianastaskevica** [comment]
Hey @teodormoq! Unfortunately, we do not plan to support old Magento versions:( But what you can try to do in your case is to downgrade the `scandipwa/catalog-graphql` version!

**Comment by teodormoq** [comment]
@lianastaskevica Aright thanks :)
