### ISSUE TITLE
Empty error message is displayed If user changes subscribe settings

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/base-theme#1711]
**Description**:
Empty error message is displayed If user changes subscribe settings

**Expected behavior**:
Error message is displayed (for example 'Internal server error' or another message

**To Reproduce**:
1. Open website
2. Log in
3. Open Newsletter Subscription page
4. Select the checkbox
5. Tap 'Save'

**Actual result:**:
Empty error message is displayed when selecting subscribe checkbox 
![image](https://user-images.githubusercontent.com/73526235/99252086-21b80900-2817-11eb-82c4-c821f601dd36.png)

**Comment by zans-laksa** [comment]
Couldn't reproduce.
Subscribe settings are updated successfuly.
Same on http://scandipwapmrev.indvp.com/
Probably this has been already fixed.

![image](https://user-images.githubusercontent.com/73945186/100122842-8cee8480-2e82-11eb-98a3-e9a8488b5273.png)
