### ISSUE TITLE
Cms blocks missing after installing theme

### ISSUE THREAD

**Issue by PiotrSzlagura** [scandipwa/base-theme#184]
**Describe the bug**
After installing scandi theme using `scandipwa/installer` package from composer and bootstrapping it, I don't have required cms blocks to run the store, and I can't open homepage.

**To Reproduce**
1. Create new magento instance using cli, and install sample magento data (also using cli)
2. Install scandipwa theme, bootstrap and build it, and set is as your storefront theme

**Expected behavior**
Main page should load without errors.

**Additional context**
I'm new to scandipwa, so I'd much appreciate any help with this issue.

**Comment by eli-l** [comment]
We are not supporting Magento sample data yet. Please use custom database and media from base repo: https://github.com/scandipwa/scandipwa-base (Quick start, step 8) and Media sections.

**Comment by PiotrSzlagura** [comment]
Thank you very much :)
