### ISSUE TITLE
Query hash is unknown

### ISSUE THREAD

**Issue by PiotrSzlagura** [scandipwa/base-theme#191]
**Describe the bug**
Hello, I was trying to load data from my custom graphql endpoint. I get 410 status code, with message saying that `Query hash is unknown`. According to documentation (https://docs.scandipwa.com/#/theme/Utilities/03-Request), this case should trigger additional request, which puts this hash and then fetches data, but nothing happens.

**To Reproduce**
Try creating your own reducer with graphql query which was never used before and is not part of the core theme.

**Expected behavior**
Data should load after sending new hash in PUT request.

**Additional context**
I'm firing this request using dispatcher which extends `QueryDispatcher`. Method firing request is QueryDispatcher's `handleData`, without any overrides.

**Comment by eli-l** [comment]
Hi @PiotrSzlagura 
We got tons of custom dispatchers done by other teams and never met this. Would you please provide more details on this, are there any JS errors in the console?
Request chaining happens in **Request.js::executeGet**.

**Comment by PiotrSzlagura** [comment]
I double checked everything and it seems that, for some reason, when response status is `410` I get error from CORS. I'm almost 100% sure that's the reason why additional request doesn't execute as it should. But my nginx configuration allows connections from every host, so I don't get why it happens... 
Or maybe this response is served from redis, not nignx? 
If so, should I enable CORS on redis?

**Comment by eli-l** [comment]
All requests are using the same Magento 2 /graphql endpoint, redis is not used directly from the client. CORS might be a reason, you shall check request/response headers or simply run everything under a single domain.

**Comment by alfredsgenkins** [comment]
Closing due inactivity.

**Comment by richardechidna** [comment]
Is there any solution for this as I am also facing this now?
Just FYI, I am a newbie
