### ISSUE TITLE
Select appearance in checkout is broken 

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#192]
**Describe the bug**
On resolution lower than Desktop the select is not a custom dropdown. It is reverted back to default select. When I change its value the appearance does not change.

**To Reproduce**
1. Resize the screen to laptop resolution (<1024px)
2. Go to `/checkout`
3. Click on dropdown of Country
4. **Notice, it is the default select**
5. Click on dropdown State
6. Select a state
7. **Notice, that state is unchanged**

**Expected behavior**
- On laptop resolution, the dropdown has a custom appearance, the selected values are changeable.
- On mobile the selected value of dropdown, should change its appearance.

**Screenshots**

The appearance of select on my laptop.

<img width="672" alt="Screen Shot 2019-06-25 at 12 27 16" src="https://user-images.githubusercontent.com/52198221/60086936-af87e580-9744-11e9-8d9c-6cf78d209dba.png">

The correct appearance of select. 

<img width="586" alt="Screen Shot 2019-06-25 at 12 27 29" src="https://user-images.githubusercontent.com/52198221/60086938-af87e580-9744-11e9-8ad6-82be3d847c52.png">

**Comment by mihailspopovs4** [comment]
Could not reproduce.
