### ISSUE TITLE
The checkout shipping step returns error

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#193]
**Describe the bug**
When submitting checkout shipping information step, the following error is displayed: `Expected a value of type "Float" but received: []`.

**To Reproduce**
1. Go to `/checkout`
2. Enter all fields
3. **Notice that the error is shown, and the loader is still loading**

**Expected behaviour**
The loader should at least stop loading, the error should not be displayed.

**Additional context**
The following changes were made in admin:
- FPT configuration (https://docs.magento.com/m2/ee/user_guide/tax/fixed-product-tax-configuration.html)

**Comment by alfredsgenkins** [comment]
Fixed as a part of `2.4.0`
