### ISSUE TITLE
The HTML tags are visible in cart

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#194]
**Describe the bug**
The HTML tags are visible to user in cart. The following text is displayed in promo block: `Add <strong> $45 </strong> to your cart and <strong> get free shipping!</strong>`

**To Reproduce**
1. Make sure at least 1 product is in cart
2. Hover on cart logo
3. **Notice the text described above**

**Expected behavior**
No HTML tags should be visible to user

**Screenshots**
<img width="510" alt="Screen Shot 2019-06-25 at 12 45 31" src="https://user-images.githubusercontent.com/52198221/60088313-22925b80-9747-11e9-8504-d841f02f3d2e.png">

**Comment by eli-l** [comment]
Fixed
