### ISSUE TITLE
Group price does not appear in checkout 

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#195]
**Describe the bug**
Group price for not logged in customers cannot be seen in mini cart dropdown and checkout.

**To Reproduce**
 1. Make sure to be logged out 
 2. Make sure to have a product with group price in the cart 
 3. Hover on cart logo 
 4. Notice a change in the price to the original one 

**Expected behavior**
For not logged in customers, the special group price in the cart should remain the same. 

**Screenshots**

<img width="704" alt="Screen Shot 2019-06-25 at 13 15 59" src="https://user-images.githubusercontent.com/52198221/60091499-65efc880-974d-11e9-9c23-ea86f9bc5676.png">

**Additional context**
The following changes were made in admin:
 - Set group price (https://docs.magento.com/m2/ce/user_guide/catalog/product-price-group.html)
 - Make sure to have selected `NOT LOGGED IN` customer group 

Works correctly, if `All groups` or `General` is selected

**Comment by alfredsgenkins** [comment]
Implemented, expect to be released in newer version of ScandiPWA.
