### ISSUE TITLE
Stock status does not change in FE

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#201]
**Describe the bug**
When the stock status is changed to `Out of Stock` in the admin panel, the status in the customer view remains as in stock even though it is not allowed to add the product to cart.

**To Reproduce**
1. On the Admin sidebar, tap `CATALOG`. Then choose `Products`
2. Choose one of the products
3. Make sure the status of the product is `Enabled`
4. In the product edit mode change the stock status to `Out of Stock`
5. Make sure to set `Display Out of Stock Products` to `Yes` ( `Stores` -> `Settings` ->  `Configuration` -> `Catalog` -> `Inventory`)
5. **Notice the text described above**

**Expected behavior**
Stock status should be changed in the FE to out of stock as well.

**Screenshots**
<img width="471" alt="Screen Shot 2019-06-27 at 14 05 48" src="https://user-images.githubusercontent.com/52198221/60262354-a6cf1500-98e6-11e9-8312-6c4124214145.png">

**Comment by atravkovs** [comment]
Fixed in https://github.com/scandipwa/base-theme/pull/329
