### ISSUE TITLE
Impossible to remove a product from cart by reducing the QTY 

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#203]
**Describe the bug**
When reducing the quantity of a product in the cart to 0 by removing products one by one, the loader does not stop loading.

**To Reproduce**
1. Add a product to the cart 
2. Reduce the quantity of it to 0  
3. **Notice that the loader is still loading**

**Expected behavior**
`You have no items in your shopping cart` should appear when the QTY of a product is reduced to 0 or the possibility to reduce the QTY should be disabled when the QTY is 1.

**Screenshots**
<img width="839" alt="Screen Shot 2019-06-27 at 16 35 17" src="https://user-images.githubusercontent.com/52198221/60271407-f3bce680-98fa-11e9-936d-e7c6c95dd4f6.png">

**Comment by alfredsgenkins** [comment]
Since `2.3.0` this is made intentional. No forever loading shown.
