### ISSUE TITLE
When product visibility is set to Search, it breaks the product page

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#204]
**Describe the bug**
When I set product visibility to `Search` the product shows up in search results only (as expected), but when I click on it the PDP breaks with 404 error. It might be caused by the request of the product made in the catalog scope (not the search).

**To Reproduce**
1. On the Admin sidebar, tap `CATALOG`. Then choose `Products`
2. Choose one of the products
3. Make sure visibility is set to `Search`
4. Go to the website, use the search field to search previously mentioned product
5. **Notice product appearing in search results** 
6. Click on the product 
7. **Notice the page throwing the 404 error**

**Expected behavior**
The product should be openable from search.

**Comment by mihailspopovs4** [comment]
Could not reproduce.
