### ISSUE TITLE
Bug with New In displaying

### ISSUE THREAD

**Issue by aleksejtsebinoga** [scandipwa/base-theme#206]
**Describe the bug**
The New In is selected on the demo store - Dresses is opened

**To Reproduce**
1. Go to Homepage
2. Click on New In category
3. See the wrong page

**Expected behavior**
New In should be showed

**Screenshots**
https://prnt.sc/o9y9af

**Desktop (please complete the following information):**
Does not matter

**Comment by lianastaskevica** [comment]
Under the "new in", the link to the dresses category is set in the menu manager. The behavior is expected.
