### ISSUE TITLE
Wrong QTY of group product in mini cart badge

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#209]
**Describe the bug**
When I add a group product to the cart, the total quantity of items in the cart badge in incorrect (shows for one item more).

**To Reproduce**
1. Go to your group product settings in the admin panel.
2. Check the default quantity of products.
3. Open a customer view and add this group product to the cart.
4. Notice having a wrong QTY of items in the mini cart badge. 

**Expected behavior**
Then total QTY of items should in the mini cart should correspond the total in cart badge. 

**Screenshots**
![Screen Shot 2019-07-05 at 19 06 33](https://user-images.githubusercontent.com/52198221/60734307-32d0e480-9f58-11e9-82d9-461c31ffc870.png)

**Comment by mihailspopovs4** [comment]
As of now Grouped Products are not supported. Code breaks in `_prepareGroupedProduct` in `Product.dispater.js`, because `items` is `undefined`.
As a result, it is not possible to reproduce this issue.

**Comment by alfredsgenkins** [comment]
This is no longer the case, as the qty of the cart is now calculated on BE.
