### ISSUE TITLE
Configurable products cannot be added to cart from My Wishlist page

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#213]
**Describe the bug**
When I try to move a configurable product to cart from My Wishlist, a warning pops up, which says that I need to choose options for my item. At the same time, configurable products cannot be edited from the wishlist. 

**To Reproduce**
1. Go to a configurable product page 
2. Add this product to the wishlist 
3. Use `add everything to cart` button 
4. **Notice the warning pops up**

**Expected behavior**
A configurable product should be editable from My Wishlist page and you should be able to add the product to cart from the wishlist.

**Screenshots**
![Screen Shot 2019-07-08 at 13 41 58](https://user-images.githubusercontent.com/52198221/60841966-be0ddc80-a1db-11e9-83fa-72a1dbb821a5.png)

**Comment by alfredsgenkins** [comment]
Since `2.4.0` the wish-list is no longer working with products, but with wish-list items. The situation described above is resolved.
