### ISSUE TITLE
Child of configurable out of stock is breaking PLP

### ISSUE THREAD

**Issue by eli-l** [scandipwa/base-theme#215]
**Describe the bug**
PLP is not working when child product of configurable is out-of-stock

**To Reproduce**
1. Enable stock management
2. Go to any child product of configurable product
3. Set 'out of stock'
4. Save, flush cache
5. PLP page is not rendered due to "TypeError: Cannot read property 'attributes' of null"

**Expected behavior**
PLP to be rendered, configurable to be rendered without unavailable option

**Comment by mihailspopovs4** [comment]
This was fixed in https://github.com/scandipwa/base-theme/pull/284
This can now be solved in BE  thanks to https://github.com/scandipwa/catalog-graphql/pull/15
Additional filter should be applied by using `addInStockFilterToCollection($collection)` on `Magento\CatalogInventory\Helper\Stock`
