### ISSUE TITLE
Cart summary does not show the price with a discount when catalog price rule is applied 

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#220]
**Describe the bug**
When I add an item with catalog price rule applied to it to cart, subtotal shows the price without a discount in the cart summary. 

**To Reproduce**
1. Make sure to have an item with catalog price rule applied to it 
2. Add the item to cart 
3. **Notice the price difference** 

**Expected behavior**
The price in the cart should also be with the discount applied.

**Screenshots**
![Screen Shot 2019-07-12 at 13 15 35](https://user-images.githubusercontent.com/52198221/61124624-ffd6a580-a4af-11e9-9388-3c24fe6abc9d.png)

**Comment by alfredsgenkins** [comment]
Fixed in: https://github.com/scandipwa/quote-graphql/releases/tag/2.0.5 Must be published in `scandipwa/base` to close the issue.
