### ISSUE TITLE
Star ranking does not reflect the average product review 

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#222]
**Describe the bug**
Star ranking does not show the average review on PRP under the product name. 

**To Reproduce**

1. Make sure to have a least one review on a product 
2. Go to this product page 
3. **Notice the star ranking under the product name ignoring the review.** 

**Expected behavior**
Star ranking should reflect the average review on the item. 

**Screenshots**
<img width="740" alt="Screen Shot 2019-07-12 at 16 09 13" src="https://user-images.githubusercontent.com/52198221/61130956-9612c780-a4c0-11e9-955e-282835b8efa2.png">

**Comment by xapiksw** [comment]
To fix this you have to clear cache storage, then star rating works as expected.

**Comment by xapiksw** [comment]
1. Ensure that in `Stores -> Attributes -> Rating` all ratings are set to the Default Store and are active;
2. Clear Cache Storage from `Tools -> Cache Management`.
