### ISSUE TITLE
Missing blocks/data is crashing app

### ISSUE THREAD

**Issue by eli-l** [scandipwa/base-theme#223]
**Describe the bug**
https://github.com/scandipwa/base-theme/pull/219
_There is an issue where all resources from batched query fails if one of the requested cms blocks does not exist.
This issue limits such functionality as enable/disable cms block from BE without updating frontend._

Issue requires revisiting.

**Comment by alfredsgenkins** [comment]
Reworked CMS blocks. Removed them from global state.
