### ISSUE TITLE
Price range does not correspond the max price of items in a category

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#228]
**Describe the bug**
The price range is not based on the maximum price of items in a category. 

**To Reproduce**
1. Go to PLP
2. **Notice price of products on the PLP is bigger than the maximum in the price range.** 

**Expected behavior**
Max price range should match the max price of items in a category.

**Screenshots**
![Screen Shot 2019-07-16 at 13 17 46](https://user-images.githubusercontent.com/52198221/61287687-1477ae00-a7ce-11e9-8f06-f0ab0b0a9741.png)

**Comment by eli-l** [comment]
Feature is already available.

**Comment by eli-l** [comment]
Fixed in https://github.com/scandipwa/base-theme/pull/256
