### ISSUE TITLE
A question about how to install

### ISSUE THREAD

**Issue by alefemafra** [scandipwa/base-theme#234]
Hello,
How to install without using docker ? 
I tried but couldn't install without using scandipwa-base

**Comment by eli-l** [comment]
Hi @alefemafra 
1. composer require scandipwa/installer
2. bin/magento setup:upgrade (install installer module)
3. bin/magento scandipwa:theme:bootstrap <vendor_name>/<theme_name>
4. cd app/design/frontend/<vendor_name>/<theme_name>
5. npm i && npm run build
6. bin/magento setup:upgrade (install new theme)
6. Go to settings/db -> enable new theme

**Comment by alefemafra** [comment]
Hello @eli-l,

Perfect, I made these steps, but it was only with white screen.

**Comment by eli-l** [comment]
We need more details to help you to sort this out. Are there any console errors, what is the server response? Did **npm run build** produce errors?

**Comment by alefemafra** [comment]
I sent a print with the errors, he tries to get from Scandipwa/pwa, he automatically tries to search there so that my created theme has another name and etc.

![Captura de Tela 2019-07-26 às 17 21 08](https://user-images.githubusercontent.com/11546384/61979374-0c87ed00-afca-11e9-9154-d4b1df9130a8.png)

**Comment by alefemafra** [comment]
hello @eli-l ,

I did these steps again to test:

1 - I created a new magento project via composer
2 - I installed magento
3 - I made the composer require scandipwa/installer
4 - bin/magento setup:upgrade (install installer module)
5 - bin/magento scandipwa:theme:bootstrap <vendor_name>/<theme_name>
6 - cd app/design/frontend/<vendor_name>/<theme_name>
7 - npm i && npm run build
8 - bin/magento setup:upgrade (install new theme)
9 - I went to admin and changed the theme

and still giving the same problem.

**Comment by alefemafra** [comment]
hello @eli-l ,

I made the installation via docker, like the video, worked right, then went to admin and activated a new theme, and got a white screen

**Comment by eli-l** [comment]
Hi @alefemafra 
I'm sorry for being silent for a while.
I was looking at your screenshot and I see that javascript bundle (application) could not be loaded. The issue might be the fact you have set web root magento root, not /pub folder: https://github.com/scandipwa/base-theme#installation-notes
In a worst case scenario it might be permission issues, please check your logs.

For docker setup - are you sure you have built your custom theme? Please confirm there is a similar content in the Magento_Theme folder: 
![Screenshot from 2019-07-30 14-21-20](https://user-images.githubusercontent.com/7448649/62125304-6ee83280-b2d5-11e9-8d35-ef01abc1c1d0.png)

**Comment by alefemafra** [comment]
Hi @eli-l ,

I changed the theme to one that I created other than Scandiweb/pwa, and went back to white screen, then checked root.phtml and it generates a static url, so I tested this and the reason for the white screen, this also happens on the docker.

![Captura de Tela 2019-07-30 às 09 41 39](https://user-images.githubusercontent.com/11546384/62129921-400a9600-b2ae-11e9-85b5-82411afad81f.png)

**Comment by eli-l** [comment]
@alefemafra 
Go to your <theme_root>/src/config/webpack.{environment}.config.js and adjust publicPath: change Scandiweb/pwa to your name
environment you are interested in is production (for npm run build) or development (for frontend service container). Or just adjust both to cover all scenarios.

**Comment by alefemafra** [comment]
hi @eli-l ,
Now it is working, but in the category and product, is giving an error in graphql, I tried to run a query in /graphql, but is having a problem, has any configuration that needs to be done?

![Captura de Tela 2019-07-31 às 09 27 44](https://user-images.githubusercontent.com/11546384/62211655-7eb75380-b375-11e9-8c22-690edd6b3f4b.png)

**Comment by eli-l** [comment]
Try to run a POST request to /graphql from i.e. postman or CURL to see an error (GraphiQl can not parse error on your screenshot).

**Comment by alefemafra** [comment]
Hello @eli-l ,
Made by Postman follows the print with the error that is returning.

![Captura de Tela 2019-08-01 às 13 48 49](https://user-images.githubusercontent.com/11546384/62311901-34ac9b80-b463-11e9-89e0-035e3bb754f1.png)

**Comment by alefemafra** [comment]
Hello @eli-l ,
Now that I realize that I was using php 7.1 and not 7.2, so is giving this error in graphql

**Comment by eli-l** [comment]
Hi @alefemafra 
Actually, there was a typo (missing typehint) that was causing this issue, but it was not present on PHP 7.2.
You can upgrade catalog-graphql to the latest version and keep PHP 7.1.
