### ISSUE TITLE
Let's configure scss-lint and eslint to consistent line paddings?

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#240]
**Is your feature request related to a problem? Please describe.**
Commonly while working on a project, the CR issues related to styles nesting and line paddings are met. TO eliminate this, we should consider additional linters. 

**Describe the solution you'd like**
Maybe we should describe this bit in eslint in https://eslint.org/docs/rules/padding-line-between-statements for example, what do you think? Also I have used this one for styles on one of my projects: https://github.com/sds/scss-lint so we could introduce this one to our project as well and then add it to CI for example, I believe by implementing it we could reduce time spent on CR as well.

**Comment by Danpiel** [comment]
Please avoid scss-lint in usage, the underlying ruby-sass is deprecated. Instead use Dart Sass or native node.js implementation (https://www.npmjs.com/package/sass).

As linter suggesting this one - https://github.com/stylelint/stylelint
