### ISSUE TITLE
Better image handling

### ISSUE THREAD

**Issue by kandrejevs** [scandipwa/base-theme#242]
the current image implementations is as follows: dafault is sqip vector image, on intersection srcset is displayed. this source set has one major problem.

the first image is webp which has fallback to generated jpg image. webp can have transparent background while jpg can't. This results on very poor experience on iphones and devices that do not support webp images if intention is to have image with transparent background. 

my proposition is to remove 2nd fallback entirely and in case webp can't be displayed and fallback to default image that was uploaded to magento (gif, png, jpg, svg). In such manner image backgrounds won't be broken, and you don't need to generate jpg image in custom path for already existing jpg images.

**Comment by alfredsgenkins** [comment]
This is no  longer the case, as we stopped using SVG placeholders.
