### ISSUE TITLE
mixins can't be overriden

### ISSUE THREAD

**Issue by kandrejevs** [scandipwa/base-theme#243]
**Describe the bug**
Some elements are styled through mixins e.g. button. Currently overriding button mixin does not work, it always use mixin from vendor styles.

**To Reproduce**
1. override `src/vendor/scandipwa/source/src/app/style/abstract/_button.scss` mixin by copying to your theme
2. Change styles
3. Styles are not updated, the old vendor mixin is still being used.

**Expected behavior**
User should be able to override mixins to style elements

**Comment by alfredsgenkins** [comment]
Related to #190

**Comment by alfredsgenkins** [comment]
The issue seems unsolved in `1.11`, must be tested!

**Comment by alfredsgenkins** [comment]
Issue reopened by mistake, closing as the bug can not be reproduced.
