### ISSUE TITLE
Related, cross-sell, and up-sell products are shown under one block 

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#248]
**Describe the bug**
When related, cross-sell, and up-sell products are added to a particular product, they all are shown under one block on PDP.

**To Reproduce**
1. In the admin view, select edit a product
2. Add related, cross-sell, and up-sell products to it 
3. **Notice, they are placed under one block on PDP**

**Expected behavior**
1. When a related product and a cross-sell product are added, they should be shown under two different blocks on PDP 
2. When an up-sell product is added, it should not be seen on PDP but should appear in the cart only.

**Comment by alfredsgenkins** [comment]
@all-contributors please add @lianastaskevica as projectManagement, bug, userTesting

**Comment by lianastaskevica** [comment]
![gif30](https://user-images.githubusercontent.com/52198221/76610069-088ce900-6521-11ea-85b1-33306705a6a0.gif)
