### ISSUE TITLE
My Account page is broken in v2.x-stable

### ISSUE THREAD

**Issue by taylormodernized** [scandipwa/base-theme#280]
**Describe the bug**
The `My Account` page throws an error about a missing query in the MyAccount.query.js when opening the page

**To Reproduce**
1. Go to the home page
2. Sign in to an existing customer account
3. Select 'My Account' from the account dropdown to go to `/my-account`
4. Observe that the page is blank, and the following is in the console:
```
MyAccountQuery.getCustomer is not a function
```

**Expected behavior**
The `My Account page` loads correctly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Brave
 - Version 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)

**Additional context**
It looks like the query for `getCustomer` was removed from the MyAccount.query.js in this commit: https://github.com/scandipwa/base-theme/commit/d409b0d8405aed7f2658b036044638e5090ad3f6#diff-07da4456b6b75c50f43b40ee72694cb0L25

**Comment by alfredsgenkins** [comment]
This is no longer the case since `2.2.0`. :)
