### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by xapiksw** [scandipwa/base-theme#287]
**Describe the bug**
Currently Gecko engine support is quite poor. Some critical issues are fixed in https://github.com/scandipwa/base-theme/pull/286 however PDP is breaking user Experience.

**To Reproduce**
Steps to reproduce the behavior (in **Firefox**):
1. Go to https://demo.scandipwa.com/product/n-81-hours-cashmere-pullover
2. Notice big paddings between elements in ProductActions section 

1. Switch to mobile view
2. Notice slider being not in position

**Expected behavior**
UI to be like in Google Chrome 

**Screenshots**
https://prnt.sc/p2t30e
https://prnt.sc/p2t2b2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 69

**Smartphone (please complete the following information):**
 - OS: Android 7.0
 - Browser Firefox Preview
 - Version Gecko Engine v69

**Comment by xapiksw** [comment]
Point 4. occasionally happens in Google Chrome as well.

**Comment by ShafeelSha** [comment]
Image postion broken in Product Deatils page first load ( Mobile View) 
![image](https://user-images.githubusercontent.com/53746963/65938561-df7c0e80-e440-11e9-8c2a-a76eaf1283b9.jpg)

**Comment by alfredsgenkins** [comment]
Fixed in `2.4.3`
