### ISSUE TITLE
I cant Install ScandiPWA basetheme in ubuntu

### ISSUE THREAD

**Issue by ShafeelSha** [scandipwa/base-theme#308]
I cant Install ScandiPWA basetheme in ubuntu , while installing it shows Error https://stackoverflow.com/questions/58009739/scandipwa-base-ssl-term-error-in-magento-2/58022250#58022250 and i am fix that using "sudo service apache2 stop" command but finally i follow video tutorial but scandipwa.local not open (404 Not Found) in my browser

**Comment by ShafeelSha** [comment]
Hai @eli-l  I'm already tried, but noway

**Comment by eli-l** [comment]
- check if all containers are running without the errors
- check port mappings for SSL-term or nginx container
- check if it is reachable on 127.0.0.1 and proper port, it will redirect you to base URL

**Comment by ShafeelSha** [comment]
PC-Name:/var/www/html/react$ git clone git@github.com:scandipwa/scandipwa-base.git
**fatal: destination path 'scandipwa-base' already exists and is not an empty directory.**
--> showing error while clone from git

**Comment by ShafeelSha** [comment]
Hello @eli-l. scandipwa-base Show the below errors when I run **docker-compose -f docker-compose.yml -f docker-compose.local.yml -f docker-compose.ssl.yml up -d** command. how can I solve this issue?


> Starting scandipwa-stable_mysql_1_9a86fc5b6c3d ... 
> Starting scandipwa-stable_elasticsearch_1_16b3ecd20ab4 ... 
> Starting scandipwa-stable_mysql_1_9a86fc5b6c3d         ... error
> 
> ERROR: for scandipwa-stable_redis_1_55d8c9f85e7d  Cannot start service redis: network c490cc8375209a7fb74256ba943d4b3e159369091ec9b83a4a68d301be241eef not found
> Starting scandipwa-stable_elasticsearch_1_16b3ecd20ab4 ... error
> ERROR: for scandipwa-stable_mysql_1_9a86fc5b6c3d  Cannot start service mysql: network c490cc8375209a7fb74256ba943d4b3e159369091ec9b83a4a68d301be241eef not found
> 
> ERROR: for scandipwa-stable_elasticsearch_1_16b3ecd20ab4  Cannot start service elasticsearch: network c490cc8375209a7fb74256ba943d4b3e159369091ec9b83a4a68d301be241eef not found
> 
> ERROR: for redis  Cannot start service redis: network c490cc8375209a7fb74256ba943d4b3e159369091ec9b83a4a68d301be241eef not found
> 
> ERROR: for mysql  Cannot start service mysql: network c490cc8375209a7fb74256ba943d4b3e159369091ec9b83a4a68d301be241eef not found
> 
> ERROR: for elasticsearch  Cannot start service elasticsearch: network c490cc8375209a7fb74256ba943d4b3e159369091ec9b83a4a68d301be241eef not found
> ERROR: Encountered errors while bringing up the project.

**Comment by eli-l** [comment]
Looks like some networking issues on your machine. You shall check if any firewall is enabled.

**Comment by alfredsgenkins** [comment]
@ShafeelSha is this resolved?

**Comment by ShafeelSha** [comment]
hai, @alfredsgenkins I can't find any solution. still, have the problem  :(

**Comment by ShafeelSha** [comment]
Hai @alfredsgenkins , Now solve this error  In the latest PWA update or before I stop the apache server, but, https://scandipwa.local URL returns Server timeout error in ubuntu. I follow the below steps
 *  Stop apache 2 service by  **sudo service apache2 stop** 
 *  **127.0.0.1       scandipwa.local** add this line in my /etc/hosts
 * follow scandi pwa **doumentation steps 1 to 9** (completd all levels without any erors)
 * Start apache  service by  **sudo service apache2 start** 
 * check localhost available or not, then  trying with https://scandipwa.local 

## Expected result : New Scandipwa theme 
## Actual result : Gateway timeout

**Comment by ShafeelSha** [comment]
Hai @alfredsgenkins  now SSL error issue solved by changing apache2 port ( default Port:80 to 8082), and I follow the base-theme documentation and all containers are running without the errors but I can't get the demo theme in **http://scandipwa.local:8082** URL 
* 127.0.0.1:8082 (localhost url)
* Install base-theme and configure pwa
* register 127.0.0.1  scandipwa.local in /etc/hosts
* now i can get Apache2 Ubuntu Default Page in the url http://scandipwa.local:8082 

>**Expected Result :: PWA Base Theme**

>**Actual Result :: Apache2 Ubuntu Default Page**

**Comment by alfredsgenkins** [comment]
Why are you mentioning Apache? 

If you are running in Docker, any servers running on machine directly must be stopped. The port of the application (ScandiPWA) is 80 and 443 HTTP and HTTPS. 

ScandiPWA is using Nginx as server.

If setup correctly, the application should open on: https://scandipwa.local/ or http:// if desired.

Also, I recommend using Slack, the latency response there is lower :)

**Comment by ShafeelSha** [comment]
Errors in log ""docker-compose -f docker-compose.yml -f docker-compose.local.yml -f docker-compose.ssl.yml logs -f app""

![image(1)](https://user-images.githubusercontent.com/53746963/66116323-24927300-e5f0-11e9-9db8-7db7066dcba2.jpg)

**Comment by tanmaigit** [comment]
Hi

I got error ```
The "https://repo.magento.com/archives/magento/framework/magento-framework-102.0.3.0.zip" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:  
app_1            |   error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed                                                                                               
app_1            |   Failed to enable crypto              
```
I made export COMPOSER_AUTH already. Please help me

**Comment by ShafeelSha** [comment]
HI @tanmaigit ,
I'm faced the same issue . in my case I'm created a new  access key form magneto official site  (https://marketplace.magento.com/customer/accessKeys/) and its work for me. please try . hope this help you, 
Thanks
