### ISSUE TITLE
Cart disappears after signing in or creating new account

### ISSUE THREAD

**Issue by kandrejevs** [scandipwa/base-theme#334]
**Describe the bug**
Items that are placed in cart as guest disappears after customer creates account or signs in.

**To Reproduce**
1. open site with clear session.
2. Add product or products to cart.
3. Create new account or sign into existing (existing account cart has to be empty)
4. previously saved items to cart disappear.

**Expected behavior**
Cart data is retained after signing in or creating account.

**Comment by Chevskis** [comment]
Video showcasing the issue:
https://drive.google.com/file/d/10E12b6D1O21vdNUUbzsYceyt2ayhTxdn/view

**Comment by alfredsgenkins** [comment]
@all-contributors please add @Chevskis for projectManagement
