### ISSUE TITLE
Logo not displaying in frontend

### ISSUE THREAD

**Issue by praveen-gurramkonda** [scandipwa/base-theme#359]
Recently i started working with scandiPWA, All going good still installation, But i am facing issues, like **Error fetching Header and Footer**
How can i solve this type issues, and Logo not displaying, Actually logo path from pub folder,
But scandiweb path from static folder only, 
I am very irritating this type issues, please anyone help me on this issue

Thankyou in Advance

**Comment by alfredsgenkins** [comment]
Logo upload support is almost here, wait for 2.5.0 release, here is a PR: https://github.com/scandipwa/base-theme/pull/355

**Comment by praveen-gurramkonda** [comment]
@alfredsgenkins Thank you for your quick reply, but how can i change logo path in core files or other way to display the logo from folder

**Comment by alfredsgenkins** [comment]
Extend `Header.component.js`, see example here: https://www.youtube.com/watch?v=TW31C4HbfC4&t=643s
