### ISSUE TITLE
Menu not displaying after adding menu items from backend

### ISSUE THREAD

**Issue by praveen-gurramkonda** [scandipwa/base-theme#360]
Hi team,
I have added menu from back-end, and i have followed all steps as per docs, but still it's not showing.
And Slider also, But sit coming some empty blocks, Please provide me some clear documents to understand more about scandiPWA, I was installed with SandiPWA installer.

Thank you

**Comment by alfredsgenkins** [comment]
Thanks for bug report @praveen-gurramkonda! You should add widget and slider as widget in Magento 2 CMS editor. Please wait until our content manger releases user-guide :) cc @all-contributors

**Comment by alfredsgenkins** [comment]
@widget sorry, for mention :(

**Comment by alfredsgenkins** [comment]
https://scandiweb.atlassian.net/wiki/spaces/SUG/pages/1758855269/Slider+Management
