### ISSUE TITLE
Reorganize the render functionality to be modulable

### ISSUE THREAD

**Issue by Animimar** [scandipwa/base-theme#378]
When we have to override a render function just to put 1 element inside, we have to copy all the funcion with all the render methods which is not the best and beautiful way to do it.

It would be nice to have the render methods separated to just introduce the element we want and not override all the others.

Maybe we could use nesting validation like https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-max-depth.md as @alfredsgenkins proposed.

**Comment by alfredsgenkins** [comment]
`"react/jsx-max-depth": [2, { "max": 2 }]` will be added.
