### ISSUE TITLE
Implement customer account features

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#39]
**Is your feature request related to a problem? Please describe.**
There is no "My Account" functional at the moment. I would like to have it!

**Describe the solution you'd like**
The following features must be implemented:

- [x] Create account
- [x] Sign in
- [x] Forget password
- [x] Reset password
- [ ] Basic "My account" page

**Additional context**
There are no styles to follow. There are no GraphQL endpoint for that. It is possible, that we would need to implement them on our own. Following features should be considered (priority from HIGH -> LOW):

- [ ] Edit account details
- [ ] Edit shipping details
- [ ] Verify email
- [ ] Resend email verification link

**Comment by vladimirsm** [comment]
Forget password is merged into account development branch
