### ISSUE TITLE
When adding to cart from Category page, the product is incorrectly displayed in cart

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#4]
**Describe the bug**
When adding to cart from a category page, the correct product configuration is not passed to cart. Wrong product information is displayed (the variant is not being chosen).

**To Reproduce**
1. Go to Category page, for example: `/category/men`
2. Choose color or size filters
3. Click "Add to cart" underneath the product card
4. Hover the cart item
5. Notice that the product added in cart is different than clicked one.

**Expected behavior**
The added to cart product from category page is the same as it is on picture. Maybe it should direct to PDP if product is configurable, or directly add to cart, if product is simple.

**Screenshots**
The product bellow is being added to cart, via the button:
![Product which is being added to cart](https://image.prntscr.com/image/-KGZVEDER8m4J3k61xD6oA.png)

This is how preview in cart looks like, notice: **the color is different from added one**:
![Product that is really added](https://image.prntscr.com/image/4tbqkGj7R2Cr7hXxwYoXhw.png)

**Additional information**
It is not clear, weather we want to open PDP or simply add to cart.

**Comment by ainarssondors** [comment]
Reserving issue for myself.

**Comment by ainarssondors** [comment]
-Cart now shows correct configurable product when adding from product list
-Button now lands to product page if multiple variants were found
in product list
Further testing should be done after an environment is established.
