### ISSUE TITLE
Console error: Zoid destroys all in checkout

### ISSUE THREAD

**Issue by rMazeiks** [scandipwa/base-theme#424]
**Describe the bug**
Upon repeat rendering of the billing step, an error message is output to the console:

![attels](https://user-images.githubusercontent.com/11248241/69753813-576a6a80-114c-11ea-8918-6528b7ab2e6c.png)

**To Reproduce**
Steps to reproduce the error on the **staging** environment (or locally; dev is down at time of reporting):
1. Add your favorite product to the cart
2. Proceed until billing step
3. Without completing checkout, click on the logo to return to the home page
4. Again, continue until the checkout step
5. Observe the above error in the console

**Expected behavior**
No error message.

Environment: Chromium or Firefox on Desktop/Linux

**Comment by alfredsgenkins** [comment]
Referenced fix in https://github.com/Luehang/react-paypal-button-v2/issues/30 and patched that issue. Should appear in next release on ScandiPWA.

**Comment by alfredsgenkins** [comment]
@yeegor please reference 8be4f728a08d514d9fad747b76fe650c17bf043e commit for fix details.
