### ISSUE TITLE
Contributors to be added [ignore]

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#430]
I will use this issue space to add awesome people to our contributors list!

**Comment by alfredsgenkins** [comment]
@all-contributors please add @joy-codilar for code, bug!

**Comment by alfredsgenkins** [comment]
@all-contributors please add @negzu for code

**Comment by alfredsgenkins** [comment]
@all-contributors please add @lsv  for code

**Comment by alfredsgenkins** [comment]
Please add @megazoor for documentation, community!

**Comment by alfredsgenkins** [comment]
@all-contributors Please add @megazoor for documentation, community!

**Comment by alfredsgenkins** [comment]
@all-contribbutors please add @yousefcisco for docs!

**Comment by alfredsgenkins** [comment]
@all-contributors please add @yousefcisco for docs!

**Comment by lianastaskevica** [comment]
![merged-1](https://user-images.githubusercontent.com/52198221/76536523-2278ee00-6485-11ea-982d-7c1ff9b32b57.gif)

**Comment by lianastaskevica** [comment]
![Group1](https://user-images.githubusercontent.com/52198221/76542214-57893e80-648d-11ea-9f2e-2f60aa25d261.png)

**Comment by lianastaskevica** [comment]
![ezgif-2-45a6f282a26a](https://user-images.githubusercontent.com/52198221/76543261-ed719900-648e-11ea-97b5-8614aa9867c7.gif)

**Comment by alfredsgenkins** [comment]
@all-contributors please add @gabunia-nick for code!

**Comment by alfredsgenkins** [comment]
@all-contributors Please add @RoboLV for code, bug

**Comment by alfredsgenkins** [comment]
@all-contributors please add @korbax for code!

**Comment by alfredsgenkins** [comment]
@all-contributors please add @bery for code! For PR https://github.com/scandipwa/quote-graphql/pull/26

**Comment by alfredsgenkins** [comment]
@all-contributors please add @Jeffrey-H for code! For PR https://github.com/scandipwa/wishlist-graphql/pull/8

**Comment by alfredsgenkins** [comment]
@all-contributors please add @raivisdejus for code! For PR https://github.com/scandipwa/route717/pull/7

**Comment by alfredsgenkins** [comment]
@all-contributors please add @artursgailis for bug, code!

**Comment by alfredsgenkins** [comment]
@all-contributors please add @bigstepdenmark for bug. For issue: https://github.com/scandipwa/quote-graphql/issues/2

**Comment by alfredsgenkins** [comment]
@all-contributors please add @fooman for bug! Related to https://github.com/scandipwa/performance/issues/3

**Comment by alfredsgenkins** [comment]
@all-contributors please add @astik for question, ideas

**Comment by alfredsgenkins** [comment]
@all-contributors please add @peterflex7 for community, ideas, help!

**Comment by alfredsgenkins** [comment]
@all-contributors please add @dfelton for code!
