### ISSUE TITLE
Add support for customizable options in products

### ISSUE THREAD

**Issue by joy-codilar** [scandipwa/base-theme#432]
**Is your feature request related to a problem? Please describe.**
Currently ScandiPWA doesn't support customizable options in products. That makes it impossible to even add a product to cart if it has a required custom option set.

**Describe the solution you'd like**
The solution would be a two part solution
1. Showing the customizable options in the product page of the theme itself
2. Adding functionality of adding to cart with custom options.

**Comment by babybeddingdesign** [comment]
any way to get this as configurable product?
![more option](https://user-images.githubusercontent.com/44744859/70392306-73d99300-19e7-11ea-9a2a-852653a34ce2.JPG)

**Comment by joy-codilar** [comment]
> any way to get this as configurable product or just to have this option on scnadiPWA?
> ![more option](https://user-images.githubusercontent.com/44744859/70392306-73d99300-19e7-11ea-9a2a-852653a34ce2.JPG)

You could create a configurable product with the 6 child product with respective names and prices, but ideally it should be a custom option

**Comment by alfredsgenkins** [comment]
@joy-codilar any progress on this? :)

**Comment by joy-codilar** [comment]
@alfredsgenkins Hey. No man. Was waiting for your response on [this](https://github.com/scandipwa/quote-graphql/pull/21) :)

**Comment by alfredsgenkins** [comment]
@joy-codilar I do not think this should be a blocker. I think it should be a dependency of a front-end PR. Because we do not usually make a feature if it is not fully supported on FE. This could lead to a confusion.

**Comment by joy-codilar** [comment]
@alfredsgenkins Makes sense. Actually while digging deeper found a couple of other dependencies as well.

1. The custom option itself needs to be shown in the cart as well (modifying the `getCartForCustomer` endpoint)
2. To show the same in the Customer's order page (modifying the `getOrderById` endpoint)
3. To add logic for adding products with required custom options to Wishlist, and to add to cart via Wishlist page (wishlist-graphql endpoints need to be changed)
4. And obviously implementing all of the above in the FE. 

Is there anything I am missing?

**Comment by alfredsgenkins** [comment]
I think not. We are not using customizable options often, so I can not validate how the really suppose to work :)

**Comment by alfredsgenkins** [comment]
Support added in PR #646

**Comment by alfredsgenkins** [comment]
File type is not yet supported.
