### ISSUE TITLE
Cannot checkout with Virtual cart

### ISSUE THREAD

**Issue by joy-codilar** [scandipwa/base-theme#474]
**Describe the bug**
Cannot checkout with a Virtual cart (i.e, all virtual products in cart) for a logged in customer having one saved address.

**To Reproduce**
1. Signup / Login
2. Add exactly one address to address book (__NOT__ more than one)
3. Add a virtual product to cart
4. Go to checkout
5. Try to proceed with selected billing address (the address previously added)

**Expected behavior**
Order should be placed with selected address as billing address

**Actual behavior**
` TypeError: Cannot read property 'city' of undefined ` comes up on the console and flow stops there.

### NOTE
Upon further inspection, I found that the `components/CheckoutBilling/CheckoutBilling.container` file's `_getAddress` function has 
`const address = addresses.find(({ id }) => id !== selectedCustomerAddressId);`
Ideally it should be 
`const address = addresses.find(({ id }) => id === selectedCustomerAddressId); ` 
if we want to find the selected address. Not sure why the condition is inversed

**Comment by alfredsgenkins** [comment]
I assume it is fixed? Notify if it is not!
