### ISSUE TITLE
404 page is not shown when attempting to open non-existing product or category [RE-open]

### ISSUE THREAD

**Issue by eli-l** [scandipwa/base-theme#48]
Bugfix for this issue was raising other defect. Must be re-opened.

**Comment by alfredsgenkins** [comment]
Please provide more details, which issue was:

> was raising other defect

@eli-l

**Comment by vladimirsm** [comment]
This issue was fixed by @eli-l  in https://github.com/scandipwa/base-theme/commit/16085eccb69057cba662ee1b7fe76cae97446cd2
