### ISSUE TITLE
GeoLite2-Country: HTTP status code: 401 Unauthorized: An account ID and license key

### ISSUE THREAD

**Issue by livioweb** [scandipwa/base-theme#490]
****Describe the bug****
Using config file /etc/GeoIP.conf
Using database directory /usr/share/GeoIP
Acquired lock file lock (/usr/share/GeoIP/.geoipupdate.lock)
Performing get filename request to https://updates.maxmind.com/app/update_getfilename?product_id=GeoLite2-Country
Not calculating MD5 sum as file does not exist: /usr/share/GeoIP/GeoLite2-Country.mmdb
Performing update request to https://updates.maxmind.com/geoip/databases/GeoLite2-Country/update?db_md5=00000000000000000000000000000000
Error retrieving updates: error updating GeoLite2-Country: error updating: unexpected HTTP status code: 401 Unauthorized: An account ID and license key are required to use this service.

I can't register this license in the project, how do I do it?

**Comment by alfredsgenkins** [comment]
Hey! 

The issue described seems unrelated. Why do you believe this is the issue on our side?

Also reproduction scenario does not seem clear.

If you are sure this issue is related to us, please reopen the issue.

**Comment by livioweb** [comment]
Hi Alfred!


[image: image.png]

When i execute the docker-compose to up the project, in determinate moment
this error show for me.

Where in this project i can configure the license of the GeoLite.
I have the license key, just a dont know where create the cofigs


Atenciosamente,
Lívio R. Lopes



*Lívio Rodrigues Lopes *Analista de Sistemas / Web Developer

*SKYPE:* liviorodrigueslopes
*TIM: *+55 (48) 9 9992-6929 (whatsapp)





Em qui., 9 de jan. de 2020 às 14:42, Alfreds Genkins <
notifications@github.com> escreveu:

**Comment by livioweb** [comment]
Crieo o geoIp.conf, e agora veio esse erro

[image: image.png]


Atenciosamente,
Lívio R. Lopes



*Lívio Rodrigues Lopes *Analista de Sistemas / Web Developer

*SKYPE:* liviorodrigueslopes
*TIM: *+55 (48) 9 9992-6929 (whatsapp)





Em qui., 9 de jan. de 2020 às 15:02, Lívio Rodrigues <
liviorodrigueslopes@gmail.com> escreveu:
