### ISSUE TITLE
Slider image path update

### ISSUE THREAD

**Issue by peterflex7** [scandipwa/base-theme#507]
An updated needed :)

import Store from 'Store';

export const WYSIWYG_MEDIA = 'wysiwyg/';
export const CATEGORY_MEDIA = 'catalog/category/';
export const PRODUCT_MEDIA = 'catalog/product';
export const LOGO_MEDIA = 'logo/';

export default (src, subPath = '') => {
    const { ConfigReducer: { secure_base_media_url } } = Store.getState();
    ## return `${ secure_base_media_url || '/media/' }${ subPath }${ src }`;
    return `${ secure_base_media_url || '/pub/media/' }${ subPath }${ src }`;
};

**Comment by alfredsgenkins** [comment]
You can do it in your custom theme. See how to edit a theme here: https://www.youtube.com/watch?v=TW31C4HbfC4&t=565s + chapter 1.
