### ISSUE TITLE
issue facing when tried to override the theme..

### ISSUE THREAD

**Issue by peterflex7** [scandipwa/base-theme#510]
Hello @alfredsgenkins,

i'm facing some issue while try to overriding sacndipwa theme with my own customised theme i'm following the same structure as you have shown in the docker-base environment the sets i'm following are these.

Note: i'm not using docker-base environment

-on Ubuntu with my own already running project on magento 2.3.3 i just install scandipwa/installer from composer generated my own theme in the theme directory run npm ci && npm run build (theme compiled successfully with default sacndipwa theme).

-add app folder in src(in my custom theme and replace css and override some classes ) and re run npm run build but after many tries their always a default theme on frontend.

**Comment by alfredsgenkins** [comment]
Can you please share what folder structure you ended up with?

About styles: it is possible they require main file to be added (unsure).

**Comment by peterflex7** [comment]
<img width="451" alt="Screenshot 2020-01-25 at 1 53 33 PM" src="https://user-images.githubusercontent.com/26825774/73118752-45554e80-3f7a-11ea-9caf-6acd12749b2d.png">

**Comment by alfredsgenkins** [comment]
Looks legit. What is inside of this folder?

**Comment by alfredsgenkins** [comment]
And what is the content of the file?

**Comment by peterflex7** [comment]
I just followed the same content and files which you have shared and guide in the video but things not taking place as yours its always uses the files from the vendor/scandipwa/source not from my theme one's.

**Comment by alfredsgenkins** [comment]
Then it should be alright. Very strange it does not function for you. Any thing you rewrote did not worked? Can you console log somewhere? It is very reliable mechanism.

**Comment by peterflex7** [comment]
ok let me share it with you can you also help me with these 2 errors ?

I'm also getting these 2 erros!

-Unchecked runtime.lastError: The message port closed before a response was received.
-did i have to generate a sw.js file in route directory or the path from the file is incorrect ?
<img width="1435" alt="Screenshot 2020-01-25 at 2 05 55 PM" src="https://user-images.githubusercontent.com/26825774/73118865-e98bc500-3f7b-11ea-9627-7f55eb649647.png">

**Comment by alfredsgenkins** [comment]
Are you using Frontend container or not?

SW is compiled into pub folder. Is your root pub?

**Comment by alfredsgenkins** [comment]
Does the issue persist? Please re-open if it is!
