### ISSUE TITLE
New Issue while trying to buld the theme

### ISSUE THREAD

**Issue by stifboy** [scandipwa/base-theme#522]
I am getting errors while trying to build the theme - Scandiweb/pwa

Ubuntu 18
Nodejs installed
npm Installed

Steps:

Go to app/design/frontend/Scandiweb/pwa 
- run npm ci

`
@host:~/public_html/app/design/frontend/Scandiweb/pwa$ npm ci

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install,
    install-test, issues, it, la, link, list, ll, ln, login,
    logout, ls, outdated, owner, pack, ping, prefix, prune,
    publish, r, rb, rebuild, remove, repo, restart, rm, root,
    run-script, s, se, search, set, show, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unlink, unpublish, unstar, up, update, upgrade, v, verison,
    version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /home/xxxx/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.5.2 /usr/share/npm
@host:~/public_html/app/design/frontend/Scandiweb/pwa$
`
When I ran npm run build I get this error
- npm run build

`> scandipwa-base@1.0.0 build /home/xxxx/public_html/app/design/frontend/Scandiweb/pwa
> npm run build-sw && webpack --config ./src/config/webpack.production.config.js

> scandipwa-base@1.0.0 build-sw /home/xxxx/public_html/app/design/frontend/Scandiweb/pwa
> webpack --config ./src/config/webpack.sw.config.js --mode=production

sh: 1: webpack: not found

npm ERR! Linux 4.15.0-76-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build-sw"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! scandipwa-base@1.0.0 build-sw: `webpack --config ./src/config/webpack.sw.config.js --mode=production`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the scandipwa-base@1.0.0 build-sw script 'webpack --config ./src/config/webpack.sw.config.js --mode=production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scandipwa-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config ./src/config/webpack.sw.config.js --mode=production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scandipwa-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scandipwa-base
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xxxx/public_html/app/design/frontend/Scandiweb/pwa/npm-debug.log

npm ERR! Linux 4.15.0-76-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! scandipwa-base@1.0.0 build: `npm run build-sw && webpack --config ./src/config/webpack.production.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scandipwa-base@1.0.0 build script 'npm run build-sw && webpack --config ./src/config/webpack.production.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scandipwa-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-sw && webpack --config ./src/config/webpack.production.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scandipwa-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scandipwa-base
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xxxx/public_html/app/design/frontend/Scandiweb/pwa/npm-debug.log
nootro@host:~/public_html/app/design/frontend/Scandiweb/pwa$`

Your help will be appreciated

Thanks

**Comment by alfredsgenkins** [comment]
It seems like an old NPM version. NPM can not find the CI command. Could you please check?

**Comment by alfredsgenkins** [comment]
The npm ci command is only present in npm version 5.7 and newer.

**Comment by alfredsgenkins** [comment]
Are you not using docker?

**Comment by alfredsgenkins** [comment]
And judging by file paths you are not :)

**Comment by linpap** [comment]
> And judging by file paths you are not :)

No I am not using docker. Do I have to use it to use the theme?

**Comment by stifboy** [comment]
> And judging by file paths you are not :)

No I am not using docker. Do I have to use it for the theme to work?

**Comment by alfredsgenkins** [comment]
No. My answer about npm version did not satisfied you? You can try `npm i` but it it not guaranteed then to work.

**Comment by alfredsgenkins** [comment]
It is just maybe we did something wrong in docker - then it could be our fault. Otherwise - it is you environment issue.

We prefer docker, as it eliminates the environment difference caused issues.

**Comment by stifboy** [comment]
> No. My answer about npm version did not satisfied you? You can try `npm i` but it it not guaranteed then to work.

I upgraded npm to 6.13.7 and everything works out great. Thank You for your help.
