### ISSUE TITLE
Custom Data From magento 2 module

### ISSUE THREAD

**Issue by peterflex7** [scandipwa/base-theme#524]
What Structure to be followed in scandipwa to make a custom component which scheam is already defined in graphql??

**Comment by alfredsgenkins** [comment]
Please define the details. What is your schema? Wat is you frontend rendering intent? There is no single approach. You could go with DataContainer or use the redux to keep this request in global state.

**Comment by peterflex7** [comment]
I have Just define the schema of myCustomModule i.e Brands(Which contains brands details like image url and etc) and i'm getting the data in graphql then just create a file with Brand.query.js in the query folder and Brand.js in type folder now i'm confused now 
How to render my brand informations in sacndipwa app what steps should i need to followed ?
should i make reducer for brand then use it in component ?
any Guide ?

**Comment by alfredsgenkins** [comment]
Well, you might need a reducer if you consider implementing the global state (more then one component needs to know about it). In any other case see how the CMSPage is implemented in latest release.

**Comment by alfredsgenkins** [comment]
It basically is a container which ability to fetch the data. :)

**Comment by peterflex7** [comment]
Alright :) Thanks @alfredsgenkins
