### ISSUE TITLE
Certain product search terms return 502 error and doesn't notify user

### ISSUE THREAD

**Issue by MistrBones** [scandipwa/base-theme#525]
**Describe the bug**
Certain search terms (i.e black, blue, grey, etc.) return a 502 error from the server.
Examples:
Slim Fit - properly returns a list of slim fit items
Dark Blue - returns 502 error
Dark Blue Slim - returns 502
Blue Slim - returns 502
Grey Slim - returns 502

**To Reproduce**
1. Go to any page on the store frontend that contains the search bar
2. Click on 'search' in the header
3. Enter an example search term
4. No products will be loaded and the placeholder items will stay in place

**Expected behavior**
An error should not be returned when searching generic search terms. Assuming this is outside the scope of ScandiPWA, proper error handling should be setup to address improper responses.

**Screenshots**
![image](https://user-images.githubusercontent.com/40408106/73644563-78f34100-462a-11ea-8bcd-4b50874b0c39.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Brave Browser
 - Version: Chromium: 79.0.3945.130

**Additional context**
Search terms such as "Large" and "Medium" return results without a problem.

**Comment by alfredsgenkins** [comment]
You are absolutely right. Very strange. Added to backlog.

**Comment by alfredsgenkins** [comment]
I love your profile pic :D

**Comment by alfredsgenkins** [comment]
And that's should be fixed by now, an Nginx issue, it turns out!
