### ISSUE TITLE
Back button clear the page on PDP

### ISSUE THREAD

**Issue by imso077** [scandipwa/base-theme#526]
When we enter the site from a direct link, to a product page, the top back button clears the site content.

reproduce:
On mobile view!
Go to https://demo.scandipwa.com/product/n-blue-slim-fit-jeans
Click the top left back button.
Site content cleared, a sno previouse history present.

I think it should go either back to Category page, or if that cannot be determined then to homepage.

On any Mobile reproducable.

**Comment by alfredsgenkins** [comment]
Will always return to homepage :)

**Comment by ejnshtein** [comment]
This issue can be closed, no issues found in version 2.14.2
