### ISSUE TITLE
Paypal payment is not working

### ISSUE THREAD

**Issue by magentoguyspk** [scandipwa/base-theme#534]
Hi,

we have one last issue of paypal
http://m2.outletpad.com/

when make order with paypal ,its doest not succesed
so I check log : this is the log report.

[2020-02-09 10:33:49] main.DEBUG: array (
'url' => 'https://api-3t.paypal.com/nvp',
'SetExpressCheckout' =>
array (
'PAYMENTACTION' => 'Sale',
'AMT' => '2.63',
'CURRENCYCODE' => 'USD',
'RETURNURL' => 'https://m2.outletpad.com/www.paypal.com/checkoutnow/error/',
'CANCELURL' => 'https://m2.outletpad.com/www.paypal.com/checkoutnow/error/',
'INVNUM' => '000000015',
'SOLUTIONTYPE' => 'Sole',
'GIROPAYCANCELURL' => 'https://m2.outletpad.com/www.paypal.com/checkoutnow/error/',
'GIROPAYSUCCESSURL' => '',
'BANKTXNPENDINGURL' => '',
'PAGESTYLE' => 'outletpad',
'SHIPPINGAMT' => '0.00',
'ITEMAMT' => '2.63',
'TAXAMT' => '0.00',
'L_NUMBER0' => NULL,
'L_NAME0' => '3.5mm Stereo In-ear Pink Smile Earphones Cute Face Design Headset',
'L_QTY0' => 1,
'L_AMT0' => '2.63',
'BUSINESS' => NULL,
'NOTETEXT' => NULL,
'EMAIL' => 'e_schnitz@hotmail.com',
'FIRSTNAME' => 'eran',
'LASTNAME' => 'schnitz',
'MIDDLENAME' => NULL,
'SALUTATION' => NULL,
'SUFFIX' => NULL,
'COUNTRYCODE' => 'IL',
'STATE' => 'Choose State',
'CITY' => 'tel aviv',
'STREET' => 'fel da',
'ZIP' => '49549',
'PHONENUM' => '3243434324',
'SHIPTOCOUNTRYCODE' => 'IL',
'SHIPTOSTATE' => 'Choose State',
'SHIPTOCITY' => 'tel aviv',
'SHIPTOSTREET' => 'fel da',
'SHIPTOZIP' => '49549',
'SHIPTOPHONENUM' => '3243434324',
'SHIPTOSTREET2' => '',
'STREET2' => '',
'SHIPTONAME' => 'eran schnitz',
'ADDROVERRIDE' => 1,
'METHOD' => 'SetExpressCheckout',
'VERSION' => '72.0',
'USER' => '****',
'PWD' => '****',
'SIGNATURE' => '****',
'BUTTONSOURCE' => 'Magento_Cart_Community',
),
'response' =>
array (
'TOKEN' => 'EC-4E8583477G239223A',
'TIMESTAMP' => '2020-02-09T10:33:49Z',
'CORRELATIONID' => '9e35e9193f302',
'ACK' => 'Success',
'VERSION' => '72.0',
'BUILD' => '54140522',
),
) [] []

I have contacted paypal support :
this is their reply:

"Thanks for contacting PayPal Merchant Technical Support.
As for your getting payment issue, your provided SetExpressCheckoutRequest API and Response information are under normal status with 'ACK' => 'Success'," with EC token EC-4E8583477G239223A.
For the payment final deduction, you have to call another API. That is DoExpressCheckoutPayment API. You can refer to the link below for details.
https://developer.paypal.com/docs/archive/nvp-soap-api/merchant/do-express-checkout-payment-nvp/
So, please call above DoExpressCheckoutPayment API to see the result and let know if you still got the problem."

 please check  can you  suggests something? is this issue with paypal site?? 

I have also prepared video for this issue

https://www.loom.com/share/33c78b4c1be7463d96b7965a59edf71e

Thanks

**Comment by magentoguyspk** [comment]
Hi
any update on this?

**Comment by lianastaskevica** [comment]
Hi! 
The issue was with Klarna. All Klarna modules were disabled except for ScandiPWA_KlarnaGraphQl, which has caused the error. Disabling ScandiPWA_KlarnaGraphQl solved the problem.

**Comment by magentoguyspk** [comment]
ok Many many Thanks ,
