### ISSUE TITLE
Multiple requests

### ISSUE THREAD

**Issue by teodormoq** [scandipwa/base-theme#548]
**Describe the bug**
For some weird reason the favicon.ico is being requested multiple times

**To Reproduce**
1. Go to 'homepage'
2. Inspect network

**Expected behavior**
Only downloads 1 time

**Screenshots**
![Screenshot 2020-03-03 at 09 38 27](https://user-images.githubusercontent.com/8639654/75757642-09f52f00-5d33-11ea-8859-07c1fa756b0f.png)

**Comment by alfredsgenkins** [comment]
Added to backlog, working

**Comment by alfredsgenkins** [comment]
Hey! This was related to compiled version of pwacompat.min.js. Updated it in the latest 2.x-dev. Must be fixed in next release.
