### ISSUE TITLE
Accessing the Search field by TAB doesn't trigger the SearchOverlay

### ISSUE THREAD

**Issue by joostm020** [scandipwa/base-theme#549]
**Describe the bug**
When you search without clicking the input first the overlay won't show up and a side effect of this is that the placeholder will remain in place before the search query.

**To Reproduce**
1. Click on the header component (see screenshot 1)
2. Press TAB to focus the search input without clicking
3. Type your search query

**Expected behavior**
When using TAB to focus the search input it should trigger the search overlay just like when you click the input.

**Screenshots**
Click location of step 1 to reproduce.
![image](https://user-images.githubusercontent.com/26708268/75780381-869c0380-5d5b-11ea-8842-952161af5dba.png)

Placeholder remains visible after typing.
![image](https://user-images.githubusercontent.com/26708268/75780697-28bbeb80-5d5c-11ea-9825-0a521f0c698e.png)

**Comment by alfredsgenkins** [comment]
yes, seems like accessibility related issue. Can you please check if focus within allows to resolve the issue? Or, possible there is a check for value required in the Search input.

**Comment by joostm020** [comment]
I added 'onFocus' and it is fixed, just not sure if we can remove 'onClick' since I don't have a way to test on mobile devices (for now with my setup).

**Comment by joostm020** [comment]
Created a pull-request https://github.com/scandipwa/base-theme/pull/551

**Comment by joostm020** [comment]
Issue resolved and PR merged.
