### ISSUE TITLE
calling cmsblock on product page 

### ISSUE THREAD

**Issue by peterflex7** [scandipwa/base-theme#556]
Hello @alfredsgenkins,

can you please guide me when i'm trying to call a cmssblock on product page its just show nothing no details were fetching from that like this 

        <CmsBlock identifiers={ ['custom-block'] } />
and also i'm trying to add Addtocart button on categorypage now where thinks works good now but when i click the button its show out of stock message from their i have passed all the req properties. 

did i made any mistake with this ?

**Comment by alfredsgenkins** [comment]
You can do it using the:
```jsx
<CmsBlock identifier="custom-block" />
```

This will automatically request and handle the block.
