### ISSUE TITLE
After installing: ConfigurableVariant cannot function as a GraphQL resolver

### ISSUE THREAD

**Issue by magextensions** [scandipwa/base-theme#577]
{errors: [{,…}]}
errors: [{,…}]
0: {,…}
debugMessage: "Magento\ConfigurableProductGraphQl\Model\Resolver\ConfigurableVariant cannot function as a GraphQL resolver"
message: "Internal server error"
extensions: {category: "internal"}
category: "internal"
trace: [{,…}, {,…},…]
0: {,…}
file: "/www/project/vendor/magento/framework/GraphQl/Schema/Type/Output/ElementMapper/Formatter/Fields.php"
line: 160
call: "Magento\Framework\GraphQl\Query\Resolver\Factory::createByClass('Magento\ConfigurableProductGraphQl\Model\Resolver\ConfigurableVariant')"
1: {,…}
2: {file: "/www/project/vendor/webonyx/graphql-php/src/Type/Definition/FieldDefinition.php", line: 90,…}
3: {file: "/www/project/vendor/webonyx/graphql-php/src/Type/Definition/ObjectType.php", line: 151,…}
4: {,…}
5: {,…}
6: {,…}
7: {,…}
8: {,…}
9: {file: "/www/project/vendor/webonyx/graphql-php/src/Language/Visitor.php", line: 410,…}
10: {file: "/www/project/vendor/webonyx/graphql-php/src/Language/Visitor.php", line: 466,…}
11: {file: "/www/project/vendor/webonyx/graphql-php/src/Language/Visitor.php", line: 273,…}
12: {file: "/www/project/vendor/webonyx/graphql-php/src/Validator/DocumentValidator.php", line: 226,…}
13: {file: "/www/project/vendor/webonyx/graphql-php/src/Validator/DocumentValidator.php", line: 118,…}
14: {file: "/www/project/vendor/webonyx/graphql-php/src/GraphQL.php", line: 149,…}
15: {file: "/www/project/vendor/webonyx/graphql-php/src/GraphQL.php", line: 98,…}
16: {file: "/www/project/vendor/magento/framework/GraphQl/Query/QueryProcessor.php", line: 79,…}
17: {file: "/www/project/vendor/magento/module-graph-ql/Controller/GraphQl.php", line: 160,…}
18: {file: "/www/project/vendor/magento/framework/Interception/Interceptor.php", line: 58,…}
19: {file: "/www/project/vendor/magento/framework/Interception/Interceptor.php", line: 138,…}
20: {file: "/www/project/vendor/scandipwa/persisted-query/src/Plugin/PersistedQuery.php", line: 96,…}
21: {file: "/www/project/vendor/magento/framework/Interception/Interceptor.php", line: 135,…}
22: {file: "/www/project/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php",…}
23: {file: "/www/project/vendor/magento/framework/Interception/Interceptor.php", line: 135,…}
24: {file: "/www/project/vendor/magento/framework/Interception/Interceptor.php", line: 153,…}
25: {file: "/www/project/generated/code/Magento/GraphQl/Controller/GraphQl/Interceptor.php", line: 26,…}
26: {file: "/www/project/vendor/magento/framework/App/Http.php", line: 116,…}
27: {file: "/www/project/generated/code/Magento/Framework/App/Http/Interceptor.php", line: 24,…}
28: {file: "/www/project/vendor/magento/framework/App/Bootstrap.php", line: 261,…}
29: {file: "/www/project/pub/index.php", line: 40,…}

**Comment by alfredsgenkins** [comment]
I think you are using Magento `2.3.4` which is not yet supported. We do out best to migrate to this Magento version.

**Comment by magextensions** [comment]
Hi Alfred,

Thank you!
Yes i use 2.3.4 i will try it with version 2.3.3 and give a update.

**Comment by magextensions** [comment]
I use now version 2.3.3 and it works like a charm!
