### ISSUE TITLE
Installed ScandiPWA on an existing Magento 2.3 instance and got the error "ChunkLoadError: "Loading chunk 13 failed".

### ISSUE THREAD

**Issue by ideabosque** [scandipwa/base-theme#585]
Installed ScandiPWA on an existing Magento 2.3 instance and got the error "ChunkLoadError: "Loading chunk 13 failed."

Here is the detail of the error message.

The resource from “http://mage23ee.local/static/version1584836223191/frontend/Scandiweb/pwa/en_US/Magento_Theme/13.en_US.bundle.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

ChunkLoadError: "Loading chunk 13 failed.
(error: http://mage23ee.local/static/version1584836223191/frontend/Scandiweb/pwa/en_US/Magento_Theme/13.en_US.bundle.js)"

**Comment by alfredsgenkins** [comment]
Can you please try with the latest version of ScandiPWA? Does the error perist?

**Comment by ideabosque** [comment]
Here is the version I installed.  What version is the last one?
"scandipwa/installer": "^2.0"

Here are the versions for node and npm.
node: v10.19.0
npm: 6.13.4

**Comment by alfredsgenkins** [comment]
According to https://github.com/scandipwa/base-theme/releases `2.11.0` but, you need to check for `scandipwa/source`. But!

Can you see this chunk generated on server? Is it returning JS?

**Comment by ideabosque** [comment]
Hello Alfreds
I check the path at *vendor/scandipwa/source* but I cannot figure it out
which release it is.  Which file should I look into?  Regarding the JS, it
seems to run the JS but with the error message.  Please check the following
screenshots.

Bibo W.

[image: image.png]

[image: image.png]

**Comment by lianastaskevica** [comment]
Hi! Please find the issue being resolved here - https://scandipwa.slack.com/archives/CD8ETGY3Y/p1587551242343200

**Comment by ideabosque** [comment]
I am not able to access the slack channel.  Can you paste the solution here?  Thanks.

**Comment by alfredsgenkins** [comment]
This url seems valid, your nginx config should point to `/pub` (this is default scenario for Magento 2). So there should be:

```bash
root <PATH_TO_MAGENTO_ROOT>/pub
```

Inside your server config
