### ISSUE TITLE
ScandiPWA Theme shows nothing after install according to Existing Magento Instructions

### ISSUE THREAD

**Issue by raulpuig** [scandipwa/base-theme#595]
Hello,

We are making an installation of your theme in order to test It, we had followed all the instructions in https://docs.scandipwa.com/#/setup/on-existing-m2 . MAGENTO 2.3.4 has sample data loaded, but when try to view the storefront the theme is like loading forever (see screenshot 3.png). 

see error here: https://magento.mitienditaenlinea.com/
<img width="1559" alt="screenshot 3" src="https://user-images.githubusercontent.com/59107667/77973817-66605580-72c3-11ea-8207-a3e35bcafea6.png">
<img width="1512" alt="screenshot 2" src="https://user-images.githubusercontent.com/59107667/77973830-6a8c7300-72c3-11ea-8855-83b2bfc1b6dc.png">
<img width="1530" alt="screenshot" src="https://user-images.githubusercontent.com/59107667/77973829-69f3dc80-72c3-11ea-8ab1-b26f3cbdb243.png">

Please could you help me to understand what are we doing wrong?.

Sorry for my poor english.

Regards,

Raul.

**Comment by alfredsgenkins** [comment]
The Magento 2.3.4 is not supported. Please prefer for now 2.3.3 instead.

**Comment by raulpuig** [comment]
Hello,

I have installed the theme on Magento 2.3.3 and have the same error. The questions are:

1. When I already have a Magento Store, do I need to import your sample database in order to run your theme?
2. Yo only have installations for local environments, but do you have any instructions in order to configure the theme in MAGENTO existing installation?.

Please help.

Regards,

Raul.

**Comment by raulpuig** [comment]
<img width="1552" alt="screenshot 3" src="https://user-images.githubusercontent.com/59107667/78403043-af692000-75c9-11ea-9c3d-e3ee60073347.png">
