### ISSUE TITLE
Doc site is not working

### ISSUE THREAD

**Issue by sunel** [scandipwa/base-theme#598]
Doc Site return 503

https://docs.scandipwa.com/#/

**Comment by alfredsgenkins** [comment]
Thanks, working on that

**Comment by raulpuig** [comment]
Hello,

Docs site not working now

https://docs.scandipwa.com/#/

it still doesn't work

**Comment by alfredsgenkins** [comment]
Should be up now https://docs.scandipwa.com/

**Comment by volanar** [comment]
https://docs.scandipwa.com/docs/overview
Do not work
