### ISSUE TITLE
Stripe payment gateway not working in scandipwa

### ISSUE THREAD

**Issue by santosh-gaggle** [scandipwa/base-theme#599]
**Describe the bug**
After the installed stripe payment method filled all stripe details in the configuration and enable some payment methods from the stripe.
now on checkout page getting an error 
{
    "errors": [
        {
            "message": "Cannot query field \"stripe_mode\" on type \"StoreConfig\".",
            "category": "graphql",
            "locations": [
                {
                    "line": 1,
                    "column": 22
                }
            ]
        },
        {
            "message": "Cannot query field \"stripe_live_pk\" on type \"StoreConfig\".",
            "category": "graphql",
            "locations": [
                {
                    "line": 1,
                    "column": 35
                }
            ]
        },
        {
            "message": "Cannot query field \"stripe_test_pk\" on type \"StoreConfig\".",
            "category": "graphql",
            "locations": [
                {
                    "line": 1,
                    "column": 51
                }
            ]
        }
    ]
}

I created schema.graphqls in stripe module and define these
after that, this issue resolved and enabled payment methods showing but without asking any payment details it placed the order. I think it should be redirected to the payment page or show the stripe payment form but nothing happen and placed the order.

when I select the card payment option then it's showing the stripe form but for others, it's not working. 

**Expected behavior**
It should be showing the payment form or redirect to payment getaway 

**Screenshots**
![image](https://user-images.githubusercontent.com/56184739/79064077-5da85000-7cc3-11ea-8f51-e3b4f6a0a78b.png)

**Additional context**
please resolve this error, I need to create a mollie payment method if stripe will working so I can create the mollie payment method with the reference of stripe

**Comment by alfredsgenkins** [comment]
Are you sure you followed the stripe installation docs of Scandipwa? https://github.com/scandipwa/base-theme/releases/tag/2.6.0

**Comment by alfredsgenkins** [comment]
I belive `composer require scandipwa/stripe-graphql` is not there.

**Comment by santosh-gaggle** [comment]
> Are you sure you followed the stripe installation docs of Scandipwa? https://github.com/scandipwa/base-theme/releases/tag/2.6.0

yes I followed these points and installed stripe according to doc


> I belive `composer require scandipwa/stripe-graphql` is not there.

yes it was missed, now I installed it 
Now this issue resolved ""message": "Cannot query field "stripe_mode" on type "StoreConfig".","

but still getting the same issue on the checkout
when I select the 'Card Payment' then stripe form is showing 
![image](https://user-images.githubusercontent.com/56184739/79103444-336d9580-7d8a-11ea-8257-2f8bd2c28331.png)

But when I select any other payment method like (it's under stripe payment method ) iDEAL or Bancontact etc
then there is not showing any  form and also not  redirect to the payment page 
it just placed the order without asking any payment details  

![image](https://user-images.githubusercontent.com/56184739/79103977-40d74f80-7d8b-11ea-8a38-f4c295ebc1f6.png)

![image](https://user-images.githubusercontent.com/56184739/79104035-5b112d80-7d8b-11ea-9b29-729835d491b6.png)

**Comment by alfredsgenkins** [comment]
Okey, I believe only card payment of stripe was implemented/tested at the moment. Possibly a few line fix to get others working, added to issues

**Comment by santosh-gaggle** [comment]
> Okey, I believe only card payment of stripe was implemented/tested at the moment. Possibly a few line fix to get others working, added to issues

 Thanks, @alfredsgenkins 
please fix this issue ASAP because Clint is waiting for mollie payment gateway 
as soon as stripe will fix then  I can create mollie payment gateway with the same way  of stripe

**Comment by alfredsgenkins** [comment]
I would prefer a contribution, instead of me fixing that. I have very limited time and this bug is not a priority currently. Unfortunately!

**Comment by alfredsgenkins** [comment]
Should of been fixes in `3.x` for Magento 2.3.5. Anything to add @yeegor ?

Closing for now.
