### ISSUE TITLE
no configured writable location to store anchors

### ISSUE THREAD

**Issue by Neelchudasama1** [scandipwa/base-theme#607]
Hello,
When i apply this(trust anchor opt/cert/scandipwa-ca.pem) command it always show me no configured writable location to store anchors.
I also tried manual as you describe in your docs.

AND one more thing when i open browser it show me "NET::ERR_CERT_AUTHORITY_INVALID".
and show me "certificate Invalid".

Please help me out asap.
Thanks.

**Comment by alfredsgenkins** [comment]
Check the FAQ for that: https://docs.scandipwa.com/docs/installation/faq/#the-err_cert_revoked-in-chrome

I do not think it is a problem with ScandiPWA. Search how to properly add certificate on trusted, on your specific OS. And always specify the OS in report!
