### ISSUE TITLE
Build minify failed 

### ISSUE THREAD

**Issue by kkwankmk** [scandipwa/base-theme#608]
Hello,
I got this error after 2.9.1 version released and `npm run build`.
If i used `npm run watch` its work.
I think it happened from implementing code splitting .

<img width="1439" alt="Screen Shot 2563-04-29 at 01 41 22" src="https://user-images.githubusercontent.com/24907222/80562162-17682600-8a11-11ea-9f15-44891bc067bc.png">

Ref. https://reactjs.org/docs/error-decoder.html/?invariant=306&args[]=function(t)%7Bvar%20n%3Dt.wrappedComponentRef%2Cr%3Dfunction(e%2Ct)%7Bvar%20n%3D%7B%7D%3Bfor(var%20r%20in%20e)0%3C%3Dt.indexOf(r)%7C%7CObject.prototype.hasOwnProperty.call(e%2Cr)%26%26(n%5Br%5D%3De%5Br%5D)%3Breturn%20n%7D(t%2C%5B%22wrappedComponentRef%22%5D)%3Breturn%20i.a.createElement(l.a%2C%7Bchildren%3Afunction(t)%7Breturn%20i.a.createElement(e%2Cs(%7B%7D%2Cr%2Ct%2C%7Bref%3An%7D))%7D%7D)%7D&args[]=

webpack v.4.43
react v.16.6.3
react-dom v.16.6.3 

Thanks.

**Comment by alfredsgenkins** [comment]
Which modification have you made to the core? Strange issue, as it says:

```
Lazy element type must resolve to a class or function.
```

And then shows the received type, which to me looks like a function:

```js
function(t){var n=t.wrappedComponentRef,r=function(e,t){var n={};for(var r in e)0<=t.indexOf(r)||Object.prototype.hasOwnProperty.call(e,r)&&(n[r]=e[r]);return n}(t,["wrappedComponentRef"]);return i.a.createElement(l.a,{children:function(t){return i.a.createElement(e,s({},r,t,{ref:n}))}})}
```

**Comment by kkwankmk** [comment]
I didn't modify everything.
I tried from scratch by install new magento2 project and `scandipwa/installer` and bootstrap theme. But still got same error. 

<img width="1440" alt="Screen Shot 2563-05-12 at 14 56 35" src="https://user-images.githubusercontent.com/24907222/81657033-c0773d80-9461-11ea-81e6-bdf8244bddb7.png">

**Comment by alfredsgenkins** [comment]
Closing, as I can not help you based on following reports. Reopen if it still happens on latest release.
