### ISSUE TITLE
Category pagination is not working properly on demo.scandipwa.com

### ISSUE THREAD

**Issue by atravkovs** [scandipwa/base-theme#609]
On current version of demo.scandipwa.com if I open some category and try to go to some page via paginator, it kinda redirects to the first page and breaks the infinite scrolling while 2nd page content is being shown. However, if page is accessed via direct URL it works.

**To Reproduce**
1. Go to https://demo.scandipwa.com/category/men
2. Scroll down to bottom of the page and click on i.e. 2nd page in paginator
3. Notice, that desired ?page=2 got removed from URL and at the bottom of the page placeholders are being shown
4. Try to "Load previous" first and then scroll down. Notice it is working as desired (both infinite scrolling and page changing in the URL)
5. Try to access 2nd page via direct URL (https://demo.scandipwa.com/category/men?page=2) and notice everything is working as well  

**Expected behavior**
After accessing page via paginator, no placeholders at the bottom should be shown and user should not be redirected to the first page in URL (https://demo.scandipwa.com/category/men)

**Desktop:**
 - OS: Win10
 - Browser: Google Chrome & Firefox

**Comment by alfredsgenkins** [comment]
Alright, noted, thanks for the report! A long time have not heard from you :')
