### ISSUE TITLE
URL rewrites not working

### ISSUE THREAD

**Issue by jayankaghosh** [scandipwa/base-theme#610]
**Describe the bug**
Going to any URL requiring urlResolver results in the message "Error fetching Menu!" showing up

**To Reproduce**
1. Go to 'https://demo.scandipwa.com/privacy-policy-cookie-restriction-mode'
2. Error fetching Menu!
3. Page doesn't load 

**Expected behavior**
It should open the proper CMS page

**Additional context**
Upon further investigation, I saw that the actual error is `Cannot query field "url_key" on type "EntityUrl".` coming from the urlResolver query, where previously in the `scandipwa/urlrewrite-graphql` module, the `url_key` field was added to `EntitiUrl`, but this module dependency has since been removed from composer for some reason, resulting in the error

**Comment by alfredsgenkins** [comment]
Wow! You are absolutely right! I will add this back ASAP, thanks for the notice!

**Comment by jayankaghosh** [comment]
Glad I could be of help :)
