### ISSUE TITLE
Issues with navigation icons on mobile

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#629]
When on mobile you open any product page then go to cart/ login/ homepage and double press that button and try to go back to cart, on first press nothing happens ( Supposed to open the last product/ product category you opened) and on second it opens all the available categories as it supposed to be. Also if you double press the homepage then go to cart/ login and now try to go to product your just gonna get redirected to homepage on first or second press ( Its is determined either you press on homepage 2 or +3 times)

Internal reference keys: `SPO-168`

**Comment by yeegor** [comment]
@lion152 I am unable to recreate this issue neither on demo nor on my local 3.0.2 instance.
Please attempt to recreate and if you don't succeed in that, this issue needs to get closed.

**Comment by yeegor** [comment]
Unable to recreate.
