### ISSUE TITLE
Checkbox has incorrect styling

### ISSUE THREAD

**Issue by ainarssondors** [scandipwa/base-theme#64]
**Describe the bug**
Field checkbox type has incorrect styling when trying to uncheck input.

**To Reproduce**
1. Open My Account in header
2. Press Create Account
3. Check the input for Newsletter
4. Try to uncheck it

**Expected behaviour**
Checkbox no longer shows checkmark when unchecking input.

**Reproduced on**
 - Browser: Chrome
 - Version: 72.0.3626.121

**Additional context**
Best if done in pure CSS.

**Comment by alfredsgenkins** [comment]
Blocks #39

**Comment by ainarssondors** [comment]
Issue was fixed in commit: 3c5e49fa936d59ff121378da62445c4da672cd00 (My-Account-Validation)
