### ISSUE TITLE
Product with tier price fails to load

### ISSUE THREAD

**Issue by krelo** [scandipwa/base-theme#651]
**Description**:
Created product with tier pricing, all groups, 2 or more at lower price.
Whenever i go to the product page it fails to load and i am presented with an error message.

Somehow the functions `formatCurrency()` and `roundPrice()` are not properly exported in TierPrices.component.js when bundled.

**Expected behavior**:
Expected to see product page with tier pricing.

**Screenshots, Video, Logs**
Console error:
`ReferenceError: formatCurrency is not defined
    at da_DK.bundle.js:1
... `

from  da_DK.bundle.js:1
`            function n() {
                var t, i;
                o()(this, n);
                for (var a = arguments.length, u = Array(a), c = 0; c < a; c++)
                    u[c] = arguments[c];
                return i = l()(this, (t = d()(n)).call.apply(t, [this].concat(u))),
                v()(f()(i), "renderDetailedTierPrice", (function(t) {
                    var n = t.qty
                      , o = t.value
                      , a = t.percentage_value
                      , u = i.props.product.price.regularPrice.amount
                      , c = u.currency
                      , l = u.value;
                    return a || (a = 1 - o / l),
                    P(e, "li", {
                        block: "TierPrices",
                        elem: "Item",
                        key: n
                    }, r("Køb %s for %s %s hver og ", n, formatCurrency(c), roundPrice(o)), P(e, "strong", null, r("gem %s%", Math.round(100 * a))))
                }
                )),
                i
            }`

**To Reproduce**:
1. Add tier pricing for qty to product.
2. Navigate to the product page.

**Versions**:
- ScandiPWA: 2.13.0
- Magento: 2.3.5

Chrome, OSX

**Additional context**:
Was able to work around this problem by moving the functions out of the return function and into constants as follows, however i am not sure why this is not working and i dont know if this is a proper solution.
[TierPrices.component.js source](https://github.com/scandipwa/base-theme/blob/4fdf949aa4b975930d682b047b2fb26acec4b59c/src/app/component/TierPrices/TierPrices.component.js#L39)
```
const formattedCurrency = formatCurrency(currency);
const roundedPrice = roundPrice(value);

        return (
            <li block="TierPrices" elem="Item" key={ qty }>
                { __(
                    'Buy %s for %s%s each and ',
                    qty,
                    formattedCurrency,
                    roundedPrice
                ) }
                <strong>
                    { __(
                        'save %s%',
                        // eslint-disable-next-line no-magic-numbers
                        Math.round(percentage_value * 100)
                    ) }
                </strong>
            </li>
        );
```

**Comment by santosh-gaggle** [comment]
Getting the same error on scandipwa 3.0

ReferenceError: formatCurrency is not defined
at nl_NL.bundle.js:1

**Comment by santosh-gaggle** [comment]
![image](https://user-images.githubusercontent.com/56184739/93374063-d4013d80-f873-11ea-9b70-c8fea914fba2.png)
