### ISSUE TITLE
Customer backend buttons not working

### ISSUE THREAD

**Issue by omegades** [scandipwa/base-theme#662]
2.3.5 M2 with all latest ScandiPWA modules per 29/05/2020.

Description:
Buttons in customer backend not working. No console output as well. (adding address to address book, edit details etc.)
Expected result:
Customer backend section to work. Being able to add an address, edit details, wishlist etc)
![afbeelding](https://user-images.githubusercontent.com/19263919/83223536-50fc9000-a17b-11ea-98de-6a98b3e18305.png)

**Comment by omegades** [comment]
Actually, everything freezes up from there. Including menu.

**Comment by alfredsgenkins** [comment]
The PR fixes this: https://github.com/scandipwa/base-theme/pull/668
