### ISSUE TITLE
Drastic degradation in google page speed score

### ISSUE THREAD

**Issue by extroniks** [scandipwa/base-theme#663]
**Description**:
This issue concerns changes in Google Page Speed rankings starting this month:
https://webmasters.googleblog.com/search/label/speed
https://blog.chromium.org/2020/05/introducing-web-vitals-essential-metrics.html

**Expected behavior**:
Decent google page speed score, at least 70+ on mobile, in order to present it as a good alternative to a normal Magento 2 website

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/16757761/83242676-160b5400-a19d-11ea-8da7-f95170f5181d.png)

**To Reproduce**:
1. Go to https://developers.google.com/speed/pagespeed/insights
2. Run analysis with URL: https://demo.scandipwa.com/
3. Wait for results

**Additional context**:
Current demonstration website visible at https://demo.scandipwa.com/

This is important from my perspective, as I mentioned in slack this is making it difficulty to convert clients to ScandiPWA or recommend it, also hard for me as a developer to present it to our company as the way forward since the score is much lower compared to some other PWA solutions.

**Comment by alfredsgenkins** [comment]
Fastly was disabled, image optimisation (webp) was disabled. I strongly believe that is the main reason behind it.

**Comment by extroniks** [comment]
Largest Contentful Paint replaced First Meaningful Paint as a metric, which I think is what is tanking the speed score.
Total blocking time is also bigger than I remember it being.

I will try out running some analysis on a local instance with inbuilt lighhouse or on a self hosted PWA but I am concerned that it won't provide the results we are hoping for.

**Comment by alfredsgenkins** [comment]
Interesting, at least from development stand-point nothing was really changed. If you have an options of testing with WEBP - try it I feel it can bring some improvement. Definitely a thing to look into, and I think Google made the metrics more precise, interesting!

**Comment by yeegor** [comment]
Lighthouse score has been improved in 2.15.0
