### ISSUE TITLE
Menu not visible on click menu button

### ISSUE THREAD

**Issue by pradipdeore1** [scandipwa/base-theme#665]
Hello Team,
The Menu is not visible or not open on click menu button
We have installed new Scandipwa them only Menu not click or  open. We have already created menu and assign to menu section in the configuration.
![menu](https://user-images.githubusercontent.com/44388206/83349292-5a3f5580-a351-11ea-8d2c-0589b797b34a.png)

**Comment by ispkumar** [comment]
I am also encountering same issue .. Nothing happens onclick of Menu.. But when I saw the developer tools the menus are rendered.

**Comment by pradipdeore1** [comment]
This issue is related for MenuOverlay.
When we click on Menu button code unable to open menu
Before  clicking
<div class="Overlay MenuOverlay">

After clicking expected result, but not added this class
<div class="Overlay Overlay_isVisible MenuOverlay MenuOverlay_isVisible">

If you put manually above classes in div then menu will comes to right side.

**Comment by pradipdeore1** [comment]
> I am also encountering same issue .. Nothing happens onclick of Menu.. But when I saw the developer tools the menus are rendered.

Better you can attached screenshot for reference

**Comment by ispkumar** [comment]
> Overlay Overlay_isVisible MenuOverlay MenuOverlay_isVisible

Yes if I put this class manually..
How to fix this issue?

**Comment by pradipdeore1** [comment]
> > Overlay Overlay_isVisible MenuOverlay MenuOverlay_isVisible
> 
> Yes if I put this class manually..
> How to fix this issue?

We need to wait for experts advice or scandipwa developer

**Comment by alfredsgenkins** [comment]
The PR fixes this: https://github.com/scandipwa/base-theme/pull/668

**Comment by pradipdeore1** [comment]
Thanks for support.
Issue resolved now.

**Comment by ispkumar** [comment]
@pradipdeore1  how did you upgrade or install this fix?

**Comment by pradipdeore1** [comment]
Copy all code in below location
https://github.com/scandipwa/base-theme/blob/2.x-dev/src/app/component/Header/Header.container.js
Replace your Header.container.js It will work
Let me know if any issue

**Comment by ispkumar** [comment]
Can you let me know here is this file located in magento

**Comment by pradipdeore1** [comment]
magento-root/vendor/scandipwa/source/src/app/component/Header/Header.container.js
replace this path once it work .

**Comment by ispkumar** [comment]
Hi @pradipdeore1  I replaced the file but still when I click on Menu nothing happens

**Comment by pradipdeore1** [comment]
clear cache and run following commands It works for Me

rm -rf pub/static/frontend/*
rm -rf var/cache/*

php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy -f
php bin/magento indexer:reindex
php bin/magento cache:flush
chmod 0777 var -R
chmod 0777 pub/static -R

npm ci
nmp run build

**Comment by ispkumar** [comment]
@pradipdeore1 : Thanks it worked..
