### ISSUE TITLE
Custom filters are not working

### ISSUE THREAD

**Issue by ispkumar** [scandipwa/base-theme#667]
Custom filters are not working

men/tops-men?customFilters=style_general:5543

================
The service request is http://______________/graphql?hash=3149125117&_filter_0={category_url_path:{eq:men/tops-men},style_general:{in:[5544]}}

This request is returning 0 products

**Comment by alfredsgenkins** [comment]
Please report version of scandipwa/catalog-graphql module :)

**Comment by ispkumar** [comment]
@alfredsgenkins  : Can you let me know how can I c heck the version ? as far as I know it is 2.13.1 as I installed through composer last week

**Comment by alfredsgenkins** [comment]
That is a theme. For any composer module, do: `composer info scandipwa/catalog-graphql`

**Comment by ispkumar** [comment]
name     : scandipwa/catalog-graphql
descrip. : ScandiPWA GraphQl extend for Catalog
keywords : magento2, module, pwa, scandipwa
versions : * 2.9.2
type     : magento2-module
license  : Open Software License 3.0 (OSL-3.0) (OSI approved) https://spdx.org/licenses/OSL-3.0.html#licenseText
homepage :
source   : [git] https://github.com/scandipwa/catalog-graphql.git c847cfc0c43e7646a1de6ae4ad3b0191c629b7cf
dist     : [zip] https://api.github.com/repos/scandipwa/catalog-graphql/zipball/c847cfc0c43e7646a1de6ae4ad3b0191c629b7cf c847cfc0c43e7646a1de6ae4ad3b0191c629b7cf
path     : public_html/vendor/scandipwa/catalog-graphql
names    : scandipwa/catalog-graphql

autoload
files
psr-4
ScandiPWA\CatalogGraphQl\ => src/

requires
magento/magento2-base ^2.3.5
scandipwa/performance ^1.0.3

**Comment by ispkumar** [comment]
@alfredsgenkins  : Can you help me here

**Comment by alfredsgenkins** [comment]
Try upgrading to 2.9.3. Are you sure products are enabled, have qty, are visible on storefront?

**Comment by ispkumar** [comment]
@alfredsgenkins other filter working like size color etc.. only style & material filter it is not forking

**Comment by alfredsgenkins** [comment]
Maybe some cached issue? Did you tried flushing Varnish cache?

I have no idea why this could happen. Maybe there indeed are no products, they are disabled?

**Comment by delkant** [comment]
Same issue here, this is my config:

Magento 2.3.5-p1
scandipwa/catalog-graphql  2.9.3

If I change to the Luma theme all filters are working as expected

**Comment by delkant** [comment]
@ispkumar any luck on this? @alfredsgenkins Any pointers on how to troubleshoot it?

**Comment by delkant** [comment]
@alfredsgenkins I have some interesting findings on this, I realized I created all the products with a not admin user, and this was causing the issue on my side(only with the scandipwa theme).

I accessed to my admin panel with the admin user and updated products.. opening them and then immediately saving them... like some how altering the ownership of the products and after that products saved by the admin where filtered correctly by they attributes. 

I tried to update the theme before doing all this, so I am not so sure if this is because something changed on my config or just because the products need to be owned by admin.

**Comment by alfredsgenkins** [comment]
Okeeey. That sounds strange. Any details on how M2 stores that? I have not thought about that edge case at all. Anything different while storing in DB?

Maybe the user is unrelated, maybe the save you did worked? 

Thanks for your findings!
