### ISSUE TITLE
Upgrade to V3 on existing magento with spwa v2

### ISSUE THREAD

**Issue by delkant** [scandipwa/base-theme#683]
**Description**:
I cannot find any documentation on how to upgrade existing Scandi PWA in general? My problem is I would like to test the V3 and get more familiar with it on my current magento installation (a plain vm, with php, mysql and magento on it, no docker) but I cannot find how to do that.

**Expected behavior**:
Documentation on how to upgrade to any available release.

**Versions**:
- ScandiPWA v3

**Comment by alfredsgenkins** [comment]
Please clarify @yeegor and let's add the guide in https://docs.scandipwa.com/docs/installation/!

**Comment by yeegor** [comment]
[Documentation](https://docs.scandipwa.com/docs/update.html) has been provided
