### ISSUE TITLE
Hardcode theme name in files

### ISSUE THREAD

**Issue by ByJacob** [scandipwa/base-theme#686]
**Description**:
Hardcode theme name in files

**Expected behavior**:
When I use a different theme name, everything compiles.

**Screenshots, Video, Logs**
```
frontend_1       | ERROR in Entry module not found: Error: Can't resolve '/var/www/public/app/design/frontend/Xcoding/pwa/src/app/index.js' in '/var/www/public/app/design/frontend/Xcoding/pwa'
frontend_1       | ERROR in Entry module not found: Error: Can't resolve '/var/www/public/app/design/frontend/Xcoding/pwa/src/sw/index.js' in '/var/www/public/app/design/frontend/Xcoding/pwa'
frontend_1       | ERROR in multi (webpack)-dev-server/client?http://localhost (webpack)/hot/dev-server.js ./src/app/index.js
frontend_1       | Module not found: Error: Can't resolve '/var/www/public/app/design/frontend/Xcoding/pwa/src/app/index.js' in '/var/www/public/app/design/frontend/Xcoding/pwa'
frontend_1       |  @ multi (webpack)-dev-server/client?http://localhost (webpack)/hot/dev-server.js ./src/app/index.js bundle[2]
frontend_1       | ERROR in multi (webpack)-dev-server/client?http://localhost (webpack)/hot/dev-server.js ./src/sw/index.js
frontend_1       | Module not found: Error: Can't resolve '/var/www/public/app/design/frontend/Xcoding/pwa/src/sw/index.js' in '/var/www/public/app/design/frontend/Xcoding/pwa'
frontend_1       |  @ multi (webpack)-dev-server/client?http://localhost (webpack)/hot/dev-server.js ./src/sw/index.js sw[2]
frontend_1       | Child html-webpack-plugin for "index.html":
frontend_1       |          Asset     Size  Chunks  Chunk Names
frontend_1       |     index.html  538 KiB       0  
frontend_1       |     Entrypoint undefined = index.html
frontend_1       |     [./node_modules/html-webpack-plugin/lib/loader.js!./src/public/index.development.html] 3.57 KiB {0} [built]
frontend_1       |     [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
frontend_1       |     [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
frontend_1       |     [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
frontend_1       | ℹ ｢wdm｣: Failed to compile.

```

**To Reproduce**:
1. Create theme with different name
2. Run everything with frontend container

**Versions**:
- ScandiPWA: 3.0.0-beta.3

**Additional context**:
Files with hardcodet theme name:
- https://github.com/scandipwa/base-theme/blob/efe2d94dc407f06e2bbaa8029ffc5b3534929dc9/scandipwa.json#L2
- https://github.com/scandipwa/base-theme/blob/efe2d94dc407f06e2bbaa8029ffc5b3534929dc9/src/config/FallbackPlugin/index.js#L47
- https://github.com/scandipwa/base-theme/blob/efe2d94dc407f06e2bbaa8029ffc5b3534929dc9/src/config/FallbackPlugin/index.js#L53
- https://github.com/scandipwa/base-theme/blob/efe2d94dc407f06e2bbaa8029ffc5b3534929dc9/src/config/webpack.production.config.js#L39

**Comment by alfredsgenkins** [comment]
Ok, maybe it is time to implement an awareness of the context? Like we can get the directory and clearly know where we are. This causing SOO many issues in 2.x, we can resolve it once and for all in 3.x!

And @ByJacob thanks for raising this up!

**Comment by alfredsgenkins** [comment]
Related to https://github.com/scandipwa/base-theme/issues/725

**Comment by yeegor** [comment]
Already implemented in 3.x as well, closing
