### ISSUE TITLE
Passing props to child components in bulk.

### ISSUE THREAD

**Issue by EdgarsJoja** [scandipwa/base-theme#687]
In many places it can be seen that components/containers pass all data to any child components which they render.
Example:
```
    render() {
        return (
            <ProductConfigurableAttributes
              { ...this.props }
              { ...this.containerFunctions }
            />
        );
    }
```

It seems to be generally a bad idea, which also looks like a general consensus in react community.
Few reasons why:
- Unnecessary re-rendering if props, that are not used change
- Hard to debug/understand from where particulate functionality is coming from. Was it injected via props, containerFunctions, state, etc.
- Can limit container props functionality. Example, if child component assigns all props in bulk on pure html, there would be warnings throws that such attribute is not valid for particular html element etc. I think I encountered something like that with "Field" component. Not sure if it was due to core theme or particular project theme, but added it as an example.

I'm sure there are plenty other reasons as well, but these are the first ones that came into mind.

Ideally, I would suggest to re-factor existing functionality to pass only necessary data, but as a minimum going forward it seems like could be a good idea.

Since I'm not that familiar with React & ScandiPWA still, I might have missed some important reason why it's like that at the moment.

Thanks

**Comment by alfredsgenkins** [comment]
I agree, that passing `{ ...this.props }` is not the best approach. The `{ ...this.containerFunctions }` is much safer.

If you feel confident enough in the task, I would ask for following:
- ESLint extension to prevent it in the future
- Fix for the code, can be for 3.x only

I agree with arguments provided. Contact @yeegor for details. I can offer you a great bounty for this task completion, please contact me personally for more details :)

**Comment by EdgarsJoja** [comment]
Hey, thanks for the response. I don't really have time to do these things myself, so this was meant more of a suggestion and to hear core devs thoughts on this matter in general.

Cheers!

**Comment by alfredsgenkins** [comment]
There is a new ESLint rule for this: `'@scandipwa/scandipwa-guidelines/jsx-no-props-destruction': 'error'`.

We will not fix this in this minor version of ScandiPWA. Instead, we will resolve it in version next major.
