### ISSUE TITLE
Checkout on create account redirects to my account

### ISSUE THREAD

**Issue by RoboLV** [scandipwa/base-theme#689]
**Description**:
In checkout (Shipping step/Address), when a user chooses to create an account (checks checkbox) and after continuing to the payment step, user gets logged in and redirected to the MyAccount.

**Expected behaviour**:
User should be logged in and stay in checkout - continue to the payment step.

**Screenshots, Video, Logs**
-

**To Reproduce**:
1. Add product to the cart
2. Goto checkout (shipping step)
3. Enter new user email and check on create an account, and add password
4. Confirm shipping data

**Versions**:
- SPWA  2.13.2
- SPWA 3.0.0 betta 3

**Additional context**:
This is bad practice to redirect from checkout when user do not excepts that.

**Comment by alfredsgenkins** [comment]
Resolved manually, thanks for the report!
