### ISSUE TITLE
Product list stays filtered when navigating back and forth to category

### ISSUE THREAD

**Issue by andsvateles** [scandipwa/base-theme#698]
**Description**:
If navigating away from a filtered category, and then back again using for example a link on the start page the products are still filtered, but no filter checkbox is selected.

**Expected behavior**:
To show all products or to show which filter is selected.

**Screenshots, Video, Logs**
https://streamable.com/qts1af

**To Reproduce**:
1. Go to 'startpage'
2. Click on 'shop audio and video' category
3. Click any filter to get a selection of products
4. Go to start page
5. Click on 'shop audio and video' category again

**Versions**:
- ScandiPWA: https://demo.scandipwa.com/

**Comment by alfredsgenkins** [comment]
Working on this at the moment. The catalog-graphql might change drastically, probably will revert to default M2 (some places), as they rewrote it to use Elasticsearch.

**Comment by alfredsgenkins** [comment]
Will require Elasticsearch 7.

**Comment by alfredsgenkins** [comment]
But the bug seems FE related, I will fix it as a part of layered navigation task. Thanks!
