### ISSUE TITLE
Checkout and cart implementation

### ISSUE THREAD

**Issue by kandrejevs** [scandipwa/base-theme#70]
**Describe the solution you'd like**
The checkout functional has to be implemented, following features are pending:

- [x] Guest checkout
- [ ] Guest -> create account checkout
- [ ] Logged in checkout

**Additional context**
The following issues has to be resolved, for checkout to be released:
- [ ] Region and country select (need to pass ID)
- [ ] Global state to toggle header and footer
- [x] Checkout GraphQL resolvers
     - [x] Estimate shipping address (for logged in & guest)
     - [x] Save shipping information (for logged in & guest)
     - [x] Save payment information (for logged in & guest)
- [x] Cart GraphQL resolvers
     - [x] Add / Update item in cart (for logged in & guest)
     - [x] Remove item from cart (for logged in & guest)
     - [x] Get items from cart (for logged in & guest)

The module which implements GraphQL endpoints for checkout can be found [here](https://github.com/scandipwa/quote-graphql).

**Comment by alfredsgenkins** [comment]
@ainarssondors Please proceed with left functional. The active branch for it: `checkout`.
