### ISSUE TITLE
Submit Review with spaces

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#720]
**Description**:
Go to any product detail page. Click on Review tab and "write a review". We are able to submit the review with spaces.

**Expected behavior**:
Empty spaces should not be considered valid input.

**Additional context**:
- Originally reported by @Senthil83 in https://github.com/scandipwa/scandipwa-base/issues/102

**Comment by alfredsgenkins** [comment]
@all-contributors please add @Senthil83 for bug!

**Comment by ejnshtein** [comment]
Should be fixed in e560c4c5248688a02a0997a971e7b2ae11e713ff.
