### ISSUE TITLE
Configurable Product card must show the "lowest - highest" price

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#723]
**Description**:
When variant products of configurable products have different price then the product card will show just the lowest price when the filter is above the lowest price it shows only the max price of that configurable product.

**Expected behavior**:
When it shows the lowest price above that in a small light text if it's written as starts from $ XXXX.XX and when it shows the max price as highest at $ XXXX.XX instead of just $ XXXX.XX

**Additional context**:
- Originally reported by @ankithg03 at https://github.com/scandipwa/scandipwa-base/issues/100

**Comment by ankith-codilar** [comment]
The issue is solved by adding a small text "As Low as above the price in PLP" as the same for PDP page when the configuration is not selected by the PR #751

**Comment by alfredsgenkins** [comment]
Thanks. I have reviewed patched few issues and merged the PR. The only known issue found - the "as low as" price is shown without considering the discount. I will move it to new issue.
