### ISSUE TITLE
WDS config for non "scandipwa.local" domains

### ISSUE THREAD

**Issue by ByJacob** [scandipwa/base-theme#725]
**Is your feature request related to a problem? Please describe.**
Allowing easy configuration of the webpack dev server for other domains

**Describe the solution you'd like**
https://github.com/scandipwa/base-theme/blob/efe2d94dc407f06e2bbaa8029ffc5b3534929dc9/src/config/webpack.development.config.js#L189

Change string 'scandipwa.local' to process.env.WEBPACK_URL_DEV

**Comment by alfredsgenkins** [comment]
made it so is uses `process.env.MAGENTO_BASEURL` (taking the host part of the URL).
