### ISSUE TITLE
Magento 2.3.5 Content Security Policies

### ISSUE THREAD

**Issue by teodormoq** [scandipwa/base-theme#740]
**Description**:
Getting a lot of errors in console

**Expected behavior**:
None errors

**To Reproduce**:
1. Go to 'website'
2. Open console'
3. See error

**Additional context**:
Make a csp_whitelist.xml file and add external urls etc. paypal and google

Read more here:
https://suneetgoyal.in/magento-2-3-5-content-security-policies-csp/

**Comment by ShafeelSha** [comment]
I Think this not a scandipwa issue . Magento 2.3.5 version added [Content Security Policies](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/security/content-security-policies.html#report-uri-configuration) , before i'm faced the same error  while upgrade magento 2.3.5 project. This is helped me to solve the issue [Magento 2.3.5-p1 CSP self unsafe-inline](https://magento.stackexchange.com/questions/312056/magento-2-3-5-p1-csp-font-src-self-unsafe-inline)
