### ISSUE TITLE
graphql Api Error 503 Backend fetch failed

### ISSUE THREAD

**Issue by ShafeelSha** [scandipwa/base-theme#758]
**Description**:
Price filter return backed fetch filed response.

**Expected behavior**:
Normal Working without any errors.  customer filter products  using price filter.

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/53746963/87667677-6dcf4000-c788-11ea-901d-9bea2357ba6e.png)

**To Reproduce**:
1. Go to 'https://demo.scandipwa.com'
2. Click on 'https://demo.scandipwa.com/category/'
3. Filter any price range 'https://demo.scandipwa.com/category/computers-peripherals-accessories/software/graphics-software?priceMax=461&priceMin=150'
4. See error in Network tab - (Developer Option)

**Additional context**:
Maybe its due to server  error

**Comment by alfredsgenkins** [comment]
I believe it was server error. Thanks for the notice!
