### ISSUE TITLE
Different shipping and billing addresses are not 100% respected during the checkout

### ISSUE THREAD

**Issue by yeegor** [scandipwa/base-theme#770]
**Description**:
- In checkout “My billing and shipping are the same” is checked even if different ones are selected in the address book

**Expected behavior**:
- If billing and shipping addresses are the same in `My Account` => the checkbox is checked
- If they differ => the checkbox is not checked and corresponding addresses are selected

**To Reproduce**:
1. Select different shipping and billing addresses in My Account
2. Go to checkout -> billing step
3. Notice that 'My billing and shipping are the same' is checked (by default)

**Versions**:
- ScandiPWA: 2.14.2

**Comment by ejnshtein** [comment]
Should be fixed in #777 .
