### ISSUE TITLE
Setup issue with JS files

### ISSUE THREAD

**Issue by Ylmzef** [scandipwa/base-theme#774]
**Description**:
Theme not loading getting errors from developer console.

**Expected behavior**:
I followed existing Magento 2 instance setup documentation.
https://docs.scandipwa.com/docs/installation/on-existing-m2/

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/8562514/88086450-afe0f300-cb87-11ea-94be-c64678f381ae.png)

I am using anohter theme name than default but theme trying still loading js file from default path.
Also there no same file from my custom theme path.
static/version1595203505546/frontend/Scandiweb/pwa/en_US/Magento_Theme/precache-manifest.d2beaba48128c2727057d06fee2a411b.js

I am using anohter locate/language (nl_NL) for storeview
static/version1595351502/frontend/XXX/PWA/nl_NL/Magento_Theme/nl_NL.bundle.min.js
But i see still "en_US.bundle.min.js" instead of "nl_NL.bundle.min.js"

**Versions**:
- ScandiPWA: * 2.14.2
magento/magento2-base ^2.3.5
scandipwa/cache ^1.0
scandipwa/catalog-graphql ^2.13.3
scandipwa/cms-graphql ^1.3
scandipwa/customer-graph-ql ^2.2.3
scandipwa/customization ^1.0.3
scandipwa/klarna-graphql ^1.1
scandipwa/locale ^1.0
scandipwa/menu-organizer ^2.0
scandipwa/paypal-graphql ^1.0
scandipwa/performance ^1.0
scandipwa/persisted-query ^2.0
scandipwa/quote-graphql ^2.13
scandipwa/reviews-graphql ^1.0
scandipwa/route717 ^1.6
scandipwa/slider-graphql ^2.0
scandipwa/store-graphql ^1.0.7
scandipwa/urlrewrite-graphql ^1.2.1
scandipwa/wishlist-graphql ^1.2

redis-cli 6.0.5
node 14.0.0
varnish 6.4.0

**Comment by ejnshtein** [comment]
I think the issue is related to your server public directory. See step 6) here for more details http://docs.scandipwa.com/docs/installation/on-existing-m2/.

In short:
> **Note**: Make sure your server is configured to point into `<MAGENTO ROOT>/pub` directory.

**Comment by Ylmzef** [comment]
Magento already running under/pub directory.

**Comment by Ylmzef** [comment]
Check screenshot it's generating worng language code for local storeview.

I see en_US.bundle js files under nl_NL storeview directory.
And on frontend it's trying to load from: 
https://XXX.XXX/static/version1596427418/frontend/XXX/PWA/nl_NL/Magento_Theme/nl_NL.bundle.min.js
 ![image](https://user-images.githubusercontent.com/8562514/89236684-87c6aa80-d5f1-11ea-951a-861caa014756.png)

**Comment by yeegor** [comment]
When you run `npm run build` the compiler uses `webpack.production.config.js`, where in the bottom part the array of languages is provided in order to compile the corresponding bundles into the `Magento_Theme` directory. By default the only language that is specified there is `en_US`, although you can specify any other language that you have a translation json for. In your case you should add `nl_NL` to that array.

**Comment by Ylmzef** [comment]
Is this correct way?

![image](https://user-images.githubusercontent.com/8562514/90262300-6dd96300-de4e-11ea-8e75-93f414bbb028.png)

**Comment by Ylmzef** [comment]
TI doesn't help me to solve problem also im getting same issue for en_US sotreview too.

**Comment by yeegor** [comment]
This is an incorrect way. You need to add your desired language below, into the array attached, next to the `en_US`
![image](https://user-images.githubusercontent.com/46347627/90266859-56ee3d00-de5d-11ea-8f04-4b76565788a3.png)

**Comment by Ylmzef** [comment]
I am getting now this issue. It doesnt generete sw.js file under pub directory.

![image](https://user-images.githubusercontent.com/8562514/90267918-8483b800-de56-11ea-96ef-a2ef99255ca7.png)

**Comment by alfredsgenkins** [comment]
This one will be patched in 2.16.1 release

**Comment by Ylmzef** [comment]
Still getting same issue..

`Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://xxxx.com/') with script ('https://xxxxx.com/sw.js'): A bad HTTP response code (404) was received when fetching the script.`
