### ISSUE TITLE
Wrong products and their quantity is shown on PLP

### ISSUE THREAD

**Issue by ybutrameev** [scandipwa/base-theme#78]
**Describe the bug**
PLP displays last loaded PDP item.

**To Reproduce**
1. Enable 3G slow in dev tools.
2. Go to any main category page to the last page.
3. Click on any product, while it is not loaded - go back to PLP.
4. Scroll all the way down.
5. Only 1 product is shown (it might also show 13/1 products or similar)

**Expected behavior**
PLP must display correct products and theirs quantity in any case.

**Screenshots**
<img width="922" alt="Screenshot 2019-04-04 at 18 45 09" src="https://user-images.githubusercontent.com/38831994/55569524-6490a000-570a-11e9-8ebd-db1331a56281.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 73.0.3683.86 (64 bit)

**Additional context**
PLP and PDP use the same query.

**Comment by alfredsgenkins** [comment]
@atachh Please test this on my-account-frontend check if it works.

**Comment by atachh** [comment]
@alfredsgenkins fixed
