### ISSUE TITLE
Redundant views in mobile transitions

### ISSUE THREAD

**Issue by yeegor** [scandipwa/base-theme#780]
**Description**:
See point 6

**Expected behavior**:
The category starts loading without showing any redundant intermediate views.

**To Reproduce**:

1. Use mobile
2. Go to category
3. Open a product
4. Press 'Search' (open category list)
5. Go to other category
6. Select different product
7. Notice that after you select a product you first see the old product, then the old category and only after that the new category starts loading

**Versions**:
- ScandiPWA: 2.14.2
- Browser version: mobile (chrome)

**Comment by alfredsgenkins** [comment]
Will be a part of 2.15.1
