### ISSUE TITLE
Tax and Discount calculation is working as shared in previous thread.

### ISSUE THREAD

**Issue by shra-jain** [scandipwa/base-theme#783]
I applied the tax settings as per https://scandiweb.atlassian.net/wiki/spaces/SUG/pages/1694761098/Taxes
But still it is not applied on frontend.

![image](https://user-images.githubusercontent.com/58976039/88373303-3e868780-cdb5-11ea-9d1b-b5bad472ea3b.png)

**Comment by alfredsgenkins** [comment]
https://docs.google.com/spreadsheets/d/1yPP6mgdGSxYkzww7Fu6a5oo1yx18idLSOo-O8pUqXig/edit?usp=sharing tested, as far as I am aware taxes and stocks are working correctly.
