### ISSUE TITLE
Composer installation issue

### ISSUE THREAD

**Issue by mgmanoj** [scandipwa/base-theme#81]
"composer require scandipwa/installer" is returning error
OS: centOS
Magento Version : 2.3.1
**Error**
Problem 1
    - scandipwa/graphql 1.0.0 requires magento/product-community-edition 2.3.0 -> satisfiable by magento/product-community-edition[2.3.0] but these conflict with your requirements or minimum-stability.
    - scandipwa/installer 1.0.0 requires scandipwa/source ^1.0 -> satisfiable by scandipwa/source[1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6].
    - scandipwa/source 1.0.0 requires scandipwa/graphql ^1.0 -> satisfiable by scandipwa/graphql[1.0.0].

**Comment by eli-l** [comment]
Hi @mgmanoj 
Thank you for raising the issue. Right now we have not yet updated all components to support 2.3.1 therefore it is not yet supported.
We are planning to release component updates to support 2.3.1 next week.

**Comment by eli-l** [comment]
@mgmanoj You can now setup ScandiPWA with Magento 2.3.1. Happy coding!
