### ISSUE TITLE
Migrate to rem for font-size in order to improve accessibility

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#818]
**Description**:
Options of Chrome like default font-size are not supported. Also docs must be updated.

**Expected behavior**:
The site should respect the preferred font-size of the customer.

**Additional context**:
Reported by Alex Miruschenko in community slack.

```
There is a trick html { font-size: 62.5% }
And then we can set to any element smth like this .a { font-size: 1.8rem } - this equal to 18px in computed styles.
In this way the user can change the browser Default font size to large or small.
If Scandi uses px font size, how can the use change the browser Default  font size?
```

**Comment by maleksandr** [comment]
I'm not sure that this implementation is convenient and correct. 
I see in commit that HTML tag has font-size 75% - $font-standard-size: 75%;
So if we have $font-standard-size: 75% and I set font-size: 1.8rem to any element, is it will be computed to 18px?

FYI @alfredsgenkins @MaksimGritcenko

**Comment by MaksimGritcenko** [comment]
> I'm not sure that this implementation is convenient and correct.
> I see in commit that HTML tag has font-size 75% - $font-standard-size: 75%;
> So if we have $font-standard-size: 75% and I set font-size: 1.8rem to any element, is it will be computed to 18px?
> 
> FYI @alfredsgenkins @MaksimGritcenko

Hello! Fixed now, thank you, @maleksandr!

**Comment by yeegor** [comment]
The fix for this issue is broken, it breaks some font sizes and icons.
Please validate your changes carefully.
