### ISSUE TITLE
The search results display attribute 'brand' as entity_id

### ISSUE THREAD

**Issue by joostm020** [scandipwa/base-theme#838]
**Description**:
The entity_id of attribute 'brand' is displayed.

**Expected behavior**:
The value of attribute 'brand' should be displayed.

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/26708268/89866233-7ceeb580-dbaf-11ea-8736-a5f938f0e056.png)

**To Reproduce**:
1. Create a dropdown attribute 'brand'
2. Set a dropdown value for one of your products
3. Go to search and lookup the product

**Versions**:
- ScandiPWA : * 2.15.0

**Comment by alfredsgenkins** [comment]
I reworked it to use value from content configuration + render in the attribute using the "proper" way.
