### ISSUE TITLE
 The "as low as" price is shown without the discount

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#842]
**Description**:
When I see "as low as" price, it does not include discount. Only base price.

**Expected behavior**:
I would expect the "as low as" price include the discount.

**Screenshots, Video, Logs**
This is how the price looks while the current variant is now selected.
![image](https://user-images.githubusercontent.com/29531824/90386010-9babeb00-e08c-11ea-9123-01722c650f3d.png)

When specific product selected, notice it has a proper base price, but with discount the "as low as" seems wrong.
![image](https://user-images.githubusercontent.com/29531824/90386050-a9fa0700-e08c-11ea-9072-966b68dd3662.png)

**Comment by alfredsgenkins** [comment]
Is Magento 2 core bug. To be closed after migration to 2.4.0. See more in original issue: https://github.com/magento/magento2/issues/27439

**Comment by yeegor** [comment]
TODO TEST
