### ISSUE TITLE
Allow extending styles without overriding components

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#843]
**Description**:
Lookup the `Component.style.extension.scss` or canonical `Component.style.override.scss` and auto-import them, if they exist.

**Additional context**:
Could provide better dev-experience. Initially asked by Phil Li on community slack.

**Comment by MaksimGritcenko** [comment]
**Response:**
1) Probably, that`s not the required feature, as we can work with a few themes and if the override files will be found in all of them, they can conflict and override each other. Possibly, it is for an extension for the Fallback plugin.
2)  It`s also possible to add this **(.override.scss)** extension into resolve field in Webpack config, to prioritize .override.scss above common .scss files.

**Comment by lion152** [comment]
Decided not to implement due to solutions logic ambiguity.
