### ISSUE TITLE
Confusing log in form email label

### ISSUE THREAD

**Issue by rMazeiks** [scandipwa/base-theme#862]
**Description**:
The "Sign in" popup email field is labeled "Login or Email". However, only emails are accepted.
![screenshot](https://user-images.githubusercontent.com/11248241/90861735-e7b0a580-e394-11ea-97ef-cb36ec34575e.png)

**Expected behavior**:
Either one of:
- Usernames (logins) are accepted as well and can be logged in with
- The label of the email field is "Email"

**To Reproduce**:
1. https://demo.scandipwa.com/
2. Click the account button
3. Enter a username in the login field

**Versions**:
Tested on Demo, as well as latest v3-beta

**Comment by alfredsgenkins** [comment]
Removed the username, will be released in upcoming 2.16.2, 3.0.1 releases.
