### ISSUE TITLE
The current user cannot perform operations on cart

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#865]
**Description**:
I've created account at demo.scandipwa.com  and made an order successfully on the website. Then i logout and tried to make an order again as a Guest it display an error:

```
The current user cannot perform operations on cart "5EknrXX8eOBR SrB42DIIMB12iNgRdnrx".
```

**Expected behavior**:
The issue should not appear.

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/29531824/91017302-bc2cf580-e5f6-11ea-84b5-d28ba1832475.png)

**Additional context**:
Originally reported by naka in community slack. https://scandipwa.slack.com/archives/CD8ETGY3Y/p1597908759006100

**Comment by ioanmeri** [comment]
Any updates on this? We are facing the same.

**Comment by drc0** [comment]
@yeegor Please reopen this issue, this problem remains if the user does not log out manually but instead the session expires. I suggest the original patch be reverted and a general solution be implemented to not repeat the logic in two places..

**Comment by yeegor** [comment]
Such issue (the one you described) already exists in our list @drc0

**Comment by drc0** [comment]
> Such issue (the one you described) already exists in our list @drc0

ok thanks, can you give me a issue number so I can follow?
