### ISSUE TITLE
Composer installation issue - dependency on magento 2.4.0?

### ISSUE THREAD

**Issue by digikeijs** [scandipwa/base-theme#873]
Hi, I want to test your nice pwa template but when I want to install through composer I get below issue. I am currently using magento 2.3.4

![image](https://user-images.githubusercontent.com/34745091/91156093-fc0dde80-e6c3-11ea-8464-ac4b7514ad6c.png)

**Comment by alfredsgenkins** [comment]
Looks like you are asking for Magento 2.4. Also, 2.3.4 is not supported, only 2.3.5. Please check you composer.json and try again on 2.3.5. The support for 2.4. will come next week.

**Comment by digikeijs** [comment]
No I am not asking for magento 2.4, my magento is set to 2.3.4 through composer. I will try on 2.3.5
