### ISSUE TITLE
Meta works unreliably

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#881]
**Description**:
The title and meta update does not work 100%.

**Expected behavior**:
It should be reliable - SEO depends on it!

**To Reproduce**:

> **Note** steps are recorded on demo.scandipwa.com

1. Homepage
2. Computers (menu)
3. First product
4. Home (logo)
5. Computers (still homepage meta).

**Additional context**:
Originally reported by mr. Tiberiu Rus in community slack!

**Comment by yeegor** [comment]
Fixed by #984
