### ISSUE TITLE
Add contribution guide

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#902]
**Description**:
We need a contribution guide!

**Comment by alfredsgenkins** [comment]
I recorded the video my own long time ago, LOL, but I think we need a textual representation of that. https://docs.scandipwa.com/docs/contribute.html

**Comment by lianastaskevica** [comment]
The textual guide is created - https://docs.scandipwa.com/how-to-tutorials-intermediate/how-to-contribute
