### ISSUE TITLE
(Mobile) Account/Login button not working in billing step and Shipping step 

### ISSUE THREAD

**Issue by lion152** [scandipwa/base-theme#904]
**Description**:

The Login/Account button is not working in the Billing step and Shipping Step.

Users can't access the login/account screen from the Shipping step or billing step when you press the button nothing happens.

**Expected behavior**:

Pressing the Account/Login button should take you to the account/login screen.

**Screenshots, Video, Logs**

![image](https://user-images.githubusercontent.com/4339464/91566058-c5e29000-e94b-11ea-843c-53a9d64b8c8a.png)

**To Reproduce**:

1. On mobile, add something to the cart
2. Enter cart
3. Press "Secure checkout"
4. Press login screen button

**Additional context**:

Tested on Chrome, Firefox, Opera

**Comment by yeegor** [comment]
Unable to recreate, hence considered fixed.
