### ISSUE TITLE
Middleware '__namespace__' error after migration from 2.16.1 to 3.0.0. stable

### ISSUE THREAD

**Issue by maleksandr** [scandipwa/base-theme#919]
**Description**:
After migration from 2.16.1 to 3.0.0. 
Next error occurs on page loading:

index.js:18 Uncaught TypeError: Cannot read property '__namespace__' of undefined

Configs from vendor were moved to Theme. Vendors configs and Theme configs were compared. Almost Everything is identical.
There is on  difference from vendor. Copywepack plugin is through the error on Theme building, so we had left the previous plugin definition:
[https://prnt.sc/u9joz6](https://prnt.sc/u9joz6)

**On page loading, in the console we have the next error. Error log:**
Screen [https://prnt.sc/u9jw9f](https://prnt.sc/u9jw9f)

`index.js:18 Uncaught TypeError: Cannot read property '__namespace__' of undefined
    at addNamespaceToMiddlewarable (index.js:18)
    at middleware (index.js:34)
    at Module.<anonymous> (Token.js:19)
    at Module.../../../../../vendor/scandipwa/source/src/app/util/Auth/Token.js (bundle.js:20099)
    at __webpack_require__ (bootstrap:837)
    at fn (bootstrap:129)
    at Module.../../../../../vendor/scandipwa/source/src/app/util/Auth/index.js (index.js:1)
    at __webpack_require__ (bootstrap:837)
    at fn (bootstrap:129)
    at Module.<anonymous> (Checkout.query.js:1)
addNamespaceToMiddlewarable @ index.js:18
middleware @ index.js:34
(anonymous) @ Token.js:19
../../../../../vendor/scandipwa/source/src/app/util/Auth/Token.js @ bundle.js:20099
__webpack_require__ @ bootstrap:837
fn @ bootstrap:129
../../../../../vendor/scandipwa/source/src/app/util/Auth/index.js @ index.js:1
__webpack_require__ @ bootstrap:837
fn @ bootstrap:129
(anonymous) @ Checkout.query.js:1
../../../../../vendor/scandipwa/source/src/app/query/Checkout.query.js @ bundle.js:13897
__webpack_require__ @ bootstrap:837
fn @ bootstrap:129
(anonymous) @ bundle.js:1200
../../../../../vendor/scandipwa/paypal-graphql/src/scandipwa/app/component/PayPal/PayPal.container.js @ bundle.js:1425
__webpack_require__ @ bootstrap:837
fn @ bootstrap:129
../../../../../vendor/scandipwa/paypal-graphql/src/scandipwa/app/component/PayPal/index.js @ index.js:1
__webpack_require__ @ bootstrap:837
fn @ bootstrap:129
(anonymous) @ index.js:1
../../../../../vendor/scandipwa/paypal-graphql/src/scandipwa/app/plugin/CheckoutPayments.plugin.js @ bundle.js:1571
__webpack_require__ @ bootstrap:837
fn @ bootstrap:129
../../../../../vendor/scandipwa/source/src/app/util/Extensions/index.js @ index.js:16
__webpack_require__ @ bootstrap:837
fn @ bootstrap:129
(anonymous) @ index.js:1
../../../../../vendor/scandipwa/source/src/app/index.js @ bundle.js:13599
__webpack_require__ @ bootstrap:837
fn @ bootstrap:129
0 @ bundle.js:73558
__webpack_require__ @ bootstrap:837
(anonymous) @ bootstrap:1016
(anonymous) @ bootstrap:1016
Show 5 more frames`

**Versions**:
- ScandiPWA: composer info scandipwa/source shows

`name     : scandipwa/source
descrip. : ScandiPWA
keywords : magento2, pwa, scandipwa, source
versions : * 3.0.0
type     : magento2-theme
license  : Open Software License 3.0 (OSL-3.0) (OSI approved) https://spdx.org/licenses/OSL-3.0.html#licenseText
source   : [git] https://github.com/scandipwa/base-theme.git 061a030e6b1f444d890d8998b06390df232ecf19
dist     : [zip] https://api.github.com/repos/scandipwa/base-theme/zipball/061a030e6b1f444d890d8998b06390df232ecf19 061a030e6b1f444d890d8998b06390df232ecf19
path     : /var/www/html/progress/src/vendor/scandipwa/source
names    : scandipwa/source

autoload
files

requires
magento/magento2-base ^2.3.5
scandipwa/cache ^1.0
scandipwa/catalog-graphql ^2.14
scandipwa/cms-graphql ^1.3
scandipwa/customer-graph-ql ^2.2.3
scandipwa/customization ^1.1
scandipwa/klarna-graphql ^1.1
scandipwa/locale ^1.0
scandipwa/menu-organizer ^2.0
scandipwa/paypal-graphql ^3.0
scandipwa/performance ^1.0
scandipwa/persisted-query ^2.3.1
scandipwa/quote-graphql ^2.14
scandipwa/reviews-graphql ^1.0
scandipwa/route717 ^1.6
scandipwa/slider-graphql ^2.0
scandipwa/store-graphql ^1.0.7
scandipwa/urlrewrite-graphql ^1.2.1
scandipwa/wishlist-graphql ^1.2
`

**Comment by yeegor** [comment]
This might be related to your dependencies' versions.
Make sure that your project's dependencies are the same as ScandiPWA core dependencies.
