### ISSUE TITLE
React route Prop type error

### ISSUE THREAD

**Issue by maleksandr** [scandipwa/base-theme#920]
**Description**:
Deleted vendor and the theme.
Made total new Build in prod and in develop modes.
There is an error on page loading

`checkPropTypes.js:20 Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`.
    in Route
    in Router (created by Context.Consumer)
    in Connect(Router) (created by RouterContainer)
    in RouterContainer (created by Context.Consumer)
    in Connect(RouterContainer) (created by App)
    in Provider (created by App)
    in Provider (created by Consumer)
    in Consumer (created by Provider)
    in Provider (created by App)
    in App`

There is an issue in React router https://github.com/ReactTraining/react-router/issues/6420
Probably we need to update react-router-dom 

**Versions**:
- ScandiPWA: 3.0.0

**Comment by yeegor** [comment]
Fixed in 3.0.2
