### ISSUE TITLE
Implement email recognition in Checkout page

### ISSUE THREAD

**Issue by lion152** [scandipwa/base-theme#923]
**Description**:

In default Magento2 if you enter an email that was registered at some point it will recognize it.

The Password field will appear and login button so that you can log in from the Checkout page.

There is no email recognition in ScandiPWA.

**To Do**

1. Implement email recognition in the Checkout page
2. If the email is recognized remove the text "Create a free account and keep track of your orders" and corresponding checkbox.
3. Hidden text and checkbox should be replaced by a password field and login button. 

**Additional context**:

![unnamed](https://user-images.githubusercontent.com/4339464/91977560-850fc000-ed2b-11ea-8448-5108bba9b1a8.png)

**Comment by ggm-dev** [comment]
Would love to see this as well.  Checkout flow is very bad right now for an existing customer who doesn't explicitly login before proceeding to checkout.
