### ISSUE TITLE
Disabled products don't return 404 error

### ISSUE THREAD

**Issue by lion152** [scandipwa/base-theme#924]
**Description**:

Disabled products are returning "404 page", however, in "Network" 404 code is not sent. Because of that for all bots page seems to be 200

**Expected behavior**:

Disabled products should return 404 code if you try to enter their URL

All pages that return 404 page should return 404 status code

**Comment by alex-vo** [comment]
Showing 404 on disabled product page fix - https://github.com/scandipwa/urlrewrite-graphql/pull/1.

**Comment by alfredsgenkins** [comment]
I think this is not a proper fix. Instead, please try editing this line: https://github.com/scandipwa/route717/blob/a4e207a8030851580f7ff6d07448759f892568db/src/Controller/Router.php#L156 this will make it return proper code in the first place.

**Comment by alfredsgenkins** [comment]
Also, please add dependency on https://github.com/scandipwa/urlrewrite-graphql/releases/tag/1.3.1

**Comment by alfredsgenkins** [comment]
@lion152 this issue looks to be resolved, but I think the proper fix would be to address this via the https://github.com/scandipwa/route717/blob/a4e207a8030851580f7ff6d07448759f892568db/src/Controller/Router.php#L156

Reopen this, if needed.
