### ISSUE TITLE
Wrong title on all products and categories by default

### ISSUE THREAD

**Issue by lion152** [scandipwa/base-theme#931]
**Description**:

"Magento commerce" is default title on all SWPWA project by default

**Expected behavior**:

Make Products' title to be products' Name by default
Categories' titles should take category name by default.

**Additional Information**

Please don't confuse with <meta name="title"> It should NOT be involved. There is no such thing as meta title.

**Comment by lion152** [comment]
Needs revalidation and/or examples

**Comment by ejnshtein** [comment]
Investigated on ScandiPWA 3.1.2 and no issues found.
