### ISSUE TITLE
Login password length and New password length don't match

### ISSUE THREAD

**Issue by ioanmeri** [scandipwa/base-theme#934]
**Description**:
I can change to a New password with 5 characters (validation error if less: "The password needs at least 5 characters.") but when I try to login with that password I get an error "Password should be at least 8 characters long"

**Versions**:
base-theme v.3 stable

**Comment by alfredsgenkins** [comment]
Indeed! A bug of Scandi from v1 now :D It can be solved by passing the password configurations to front-end, but then regex checks might differ.

I am leaning towards implementing it via BE check only - remove any checks on FE. What do you think?

**Comment by ioanmeri** [comment]
Maybe use only basic client-side build-in form validation like "This field is required" and "Please enter a valid email address" to avoid these ajax calls. Then I guess the strict validation should be coming from BE. 

Since same rules are used in multiple places, a request can be made every time (not that bad for password validation) or rules could be fetched and cached once like store configuration. 
With second approach invalidation must happen when rules change in BE ( and force logout user if a request passes through and is invalid - client has changed the rules ) and it gets complex. 

I think basic build-in and BE check is fine for this

**Comment by ioanmeri** [comment]
Also checkValidity() method on forms in combination with noValidate and required comes handy for displaying custom styles.

**Comment by lion152** [comment]
Unable to reproduce in 3.0.2
