### ISSUE TITLE
Apply Discount Code in Billing Step

### ISSUE THREAD

**Issue by ioanmeri** [scandipwa/base-theme#938]
**Description**:
In billing step, be able to enter a discound code created as a cart price rule.

**Additional context**:
The coupon code and discount appears in Order Summary if ```cardData.discount_amount``` is set in graphql response (set from stock M2)

**Comment by lion152** [comment]
Hello, isn't this already mentioned here? https://github.com/scandipwa/base-theme/issues/906

Or am I missing something?

**Comment by ioanmeri** [comment]
Yes I'm sorry, that's true !
