### ISSUE TITLE
Bootstrapping theme issue using installer

### ISSUE THREAD

**Issue by mgmanoj** [scandipwa/base-theme#95]
**Describe the bug**
After installation using composer when doing bootstrapping using command php bin/magento scandipwa:theme:bootstrap Scandiweb/pwa returns error

**To Reproduce**
Steps to reproduce the behaviour:
1. composer require scandipwa/installer
2. "php bin/magento module:enable" all scandiweb modules
3. php bin/magento scandipwa:theme:bootstrap Scandiweb/pwa
4. Then return error /public_html/vendor/scandipwa/source/src/app/route/RouterTem  
  plate/index.js" file doesn't exist.  

**Expected behavior**
Bootstrapping will finish successfully without errors

**Additional context:**
 - OS: cent OS 7
 - Version : magento 2.3.1

**Comment by alfredsgenkins** [comment]
Related to #94 It is required to release a new theme version. Please update @eli-l when will be fixed!

**Comment by eli-l** [comment]
Issue solved.
For _scandipwa/source_ < 1.2.1 will be used _scandipwa/installer_ 1.0.x

Please **upgrade** _scandipwa/source_ and _scandipwa/installer_.
