### ISSUE TITLE
Safari iPad user-agent issue

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#950]
**Description**:
Hey guys, I am couple of days before launching new ScandiPWA project on version 2 and I have came up with an issue on Safari iPad version. For some reason, iPad thinks it is on a desktop version so there is no way of going to cart and finishing checkout. This behavior can be seen on demo.scandipwa.com. It all works however on Chrome on iPad. Have anyone come across this one? Is there an easy fix? Thanks in advance!

**Additional context**:
Safari iPad 9.7 is not using correct navigator user agent. Only thing I could think of how to fix this is to add a check for screen width, which is not fortunate but in the end this hack works and all works well on Safari iPad now

Reported by Vojta Ešner in community slack

**Comment by ejnshtein** [comment]
Also https://github.com/scandipwa/base-theme/issues/956

**Comment by ejnshtein** [comment]
Currently, we have 3 different styles on the frontend: mobile, desktop, and in the middle tablet view.
Maybe we should remove of tablet view?
This way we'll reduce amount of logic in components and simplify development.
Many tablets, including iPad, use desktop version as default anyway.

**Comment by yeegor** [comment]
@ejnshtein please prioritize this task.

**Comment by ejnshtein** [comment]
We've decided that in the next update tablets will use desktop view.
