### ISSUE TITLE
Going into landscape mode in Menu on IPad pro breaks the menu

### ISSUE THREAD

**Issue by lion152** [scandipwa/base-theme#956]
**Description**:
If you go into the menu on IPad Pro and go into Landscape mode the menu breaks

**Expected behavior**:

The menu in Landscape should render properly on IPad pro

**Screenshots, Video, Logs**

![image](https://user-images.githubusercontent.com/4339464/92577849-cce69800-f293-11ea-803e-0901ae5d1cf3.png)

![image](https://user-images.githubusercontent.com/4339464/92577914-de2fa480-f293-11ea-996b-2569b73547b4.png)

**To Reproduce**:
1. Go to demo.scandipwa.com
2. Inspect the website, switch to mobile view, select IPad Pro as your device
3. Go into "Menu"
4. Switch to landscape mode
5. Observe...

**Comment by yeegor** [comment]
Originally reported here: https://forum.scandipwa.com/t/menu-not-showing-on-ipad-pro/188/10

**Comment by magexpert** [comment]
Seems that issue also occurs on ipad pro using chrome. in landscape and portret. Issue is now many days old and user is getting complains from his customers.
