### ISSUE TITLE
Extension is called twice if initial component is overwritten in app/design

### ISSUE THREAD

**Issue by denissdubinin** [scandipwa/base-theme#959]
**Description**:
We noticed our plugins are called twice if initial component (to which we create plugin) is overwritten in `app/design` and has namespace.

The result is that object has 2 equal namespaces ([screenshot](https://tppr.me/PR8Gf)) what cause plugin to call twice in loop.

**Expected behavior**:
* Plugin is called once for component that is overwritten.

**To Reproduce**:
1. Overwrite component in `app/design`
2. Create plugin for overwritten component
3. See it's called twice.

**Versions**:
- ScandiPWA: 3.0.0

**Additional context**:
As a temporary solution, we removed namespaces from app/design components.

**Comment by yeegor** [comment]
Fixed by https://github.com/scandipwa/base-theme/commit/4f57bc10e1b8e82bb7ed682561a6d4b80e5eb163
