### ISSUE TITLE
Color swatches broken

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#967]
**Description**:
The color swatch no loger return the proper value.

**Expected behavior**:
Should show colors!

**Screenshots, Video, Logs**
See here: https://scandipwapmrev.indvp.com/default/women

**Additional context**:
Reported by community memeber Mustafa Shaban.

Possible could be related to **visible on catalog pages**.

**Comment by alfredsgenkins** [comment]
Mr. Athar reported following:

Just had the same issue in scandipwa version 3 while it was fine on version 2.
I'm not sure if you are having the same bug but just for testing can you try the following:
Open the file: vendor/scandipwa/catalog-graphql/src/Model/Resolver/Aggregations/SwatchData.php
and change lines 64 till 66 to:

```php
if (is_numeric($optionId)) {
    $optionId = (int)$optionId;
    $this->swatches->addAttributeOptionId($optionId);
}
```

**Comment by danielsstabulis** [comment]
Hi, I wasn't able to reproduce the following issue on the latest 3.0.2 version. It seems that everything works fine. Is it possible for Mr. Athar to report which version of scandiPWA does he uses.
Please see the reference where everything works fine (scandiPWA version 3.0.2): 
https://uk-demo.scandipwa.com/women.html

**Comment by bahramdavodi** [comment]
@danielsstabulis the issue is not fixed. this problem happening when the swatch option id and category id is the same.

**Comment by alfredsgenkins** [comment]
Th fix implemented by @robertsbriedis did resolve the issue, but the solution I would like to see should come from BE. Should we open new issue for that @lianastaskevica ?
