### ISSUE TITLE
Incorrect imports from store break the GTM extension.

### ISSUE THREAD

**Issue by yeegor** [scandipwa/base-theme#975]
**Description**:
After 2.15.0 store/index.js and query/index.js files have been deprecated, hence all the imports related to these places should be rewritten. In the GTM extension this has not yet been done.

**Expected behavior**:
The application works properly with GTM extension

**To Reproduce**:
1. Install the GTM extension
2. Go to the website

**Versions**:
- ScandiPWA: 3.0.0+ w/ GTM extension

**Additional context**:
Originally reported here: https://forum.scandipwa.com/t/installation-of-gtm-extension/246

**Comment by yeegor** [comment]
Going to be fixed in https://github.com/yeegor/gtm-graphql/pull/3

**Comment by lianastaskevica** [comment]
Fixed in https://github.com/yeegor/gtm-graphql/pull/3
